// Salty Academy game data · part 1 (P1, P2, M1, M2)
// Schema: cards {t term, d meaning, s say-it}, quiz {q, a[0]=correct, why},
// translate {setup, a[0]=best, why}, diagnose {say, a[0]=real problem, why}
window.ACADEMY_PART1 = [
{
  id: "p1", num: "P1", title: "Why Websites Lose Customers", icon: "🌊",
  read: "modules/reel-school-01.html",
  cards: [
    {id:"f.p1.conversion.a", c:["c.p1.conversion"], t:"Conversion", d:"The moment a visitor does the thing you wanted: books, buys, messages, calls.", s:"turning visitors into customers"},
    {id:"f.p1.cta.a", c:["c.p1.cta"], t:"Call to action (CTA)", d:"The button or line that tells the visitor what to do next.", s:"one clear next step"},
    {id:"f.p1.hero.a", c:["c.p1.hero"], t:"Hero", d:"The big first section of a page: headline, image, main button.", s:"the first thing people see"},
    {id:"f.p1.fold.a", c:["c.p1.fold"], t:"Above the fold", d:"Everything visible before scrolling. Prime real estate.", s:"before anyone even scrolls"},
    {id:"f.p1.speed.a", c:["c.p1.speed"], t:"Load time", d:"How long from tap to usable page.", s:"how fast it opens"},
    {id:"f.p1.speed.b", c:["c.p1.speed"], t:"First paint", d:"When the first real content appears on screen.", s:"the moment something shows up"},
    {id:"f.p1.bounce.a", c:["c.p1.bounce"], t:"Bounce", d:"A visitor who lands and leaves without doing anything.", s:"people who leave straight away"},
    {id:"f.p1.friction.a", c:["c.p1.friction"], t:"Friction", d:"Anything that makes the visitor think, wait, or guess.", s:"anything that makes people hesitate"},
    {id:"f.p1.proof.a", c:["c.p1.proof"], t:"Social proof", d:"Evidence others already trust you: reviews, clients, real numbers.", s:"proof you have done this before"},
    {id:"f.p1.value-prop.a", c:["c.p1.value-prop"], t:"Value proposition", d:"The one sentence explaining what you offer, for whom, and why you.", s:"what you do, in one sentence"},
    {id:"f.p1.five-second.a", c:["c.p1.five-second"], t:"Five second test", d:"Show a homepage for 5 seconds, then ask: what, for whom, what next?", s:"the five second test"},
    {id:"f.p1.choice-overload.a", c:["c.p1.choice-overload"], t:"Choice overload", d:"Too many options slow decisions down until no decision happens.", s:"too many choices means no choice"},
    {id:"f.p1.audit.a", c:["c.p1.audit"], t:"Audit", d:"A structured review of a site against these principles, ending in a fix list.", s:"we look at your site the way a customer does"},
    {id:"f.p1.credibility.a", c:["c.p1.credibility"], t:"Credibility", d:"Whether a stranger decides you look trustworthy and current.", s:"whether strangers trust you"}
  ],
  quiz: [
    {id:"q.p1.speed.a", c:["c.p1.speed","c.p1.bounce"], q:"Your customer opens your site on slow hotel wifi. Three seconds pass with nothing showing. What share of people like her are already gone?", a:["More than half","About a quarter","About three quarters","Almost nobody"], why:"Google's own numbers: past three seconds, more than half of mobile visitors are already gone."},
    {id:"q.p1.credibility.a", c:["c.p1.credibility"], q:"A stranger lands on your homepage for the first time. What share of people decide right then if your business feels real?", a:["About three in four","Around one in four","About half of all visitors","Nearly everyone who visits"], why:"Stanford's web credibility research: three quarters of first impressions are decided by pixels, not by anything you actually did."},
    {id:"q.p1.five-second.a", c:["c.p1.five-second"], q:"You flash your homepage at a friend for five seconds, then hide it. She can say what you sell and who it's for. What's the third thing she needs to answer?", a:["What do I do next?","How much does it cost?","Where are they located?","How long have they existed?"], why:"Miss any of the three and a real visitor already tapped back."},
    {id:"q.p1.bounce.b", c:["c.p1.bounce","c.p1.speed"], q:"Two friends look at your site. One says it's ugly. One says it took forever to load. Which complaint should worry you more?", a:["Slow. Nobody complains, they just leave","Ugly. Looks decide first impressions of trust","Neither. Both are simple fixes later on","Slow, since Google quietly removes slow sites"], why:"Nobody emails you about a slow site. They just tap back, and you never hear about the customer you lost."},
    {id:"q.p1.salesperson.a", c:["c.p1.salesperson"], q:"Picture your website as a salesperson greeting every visitor. What should a good one do, in order?", a:["Open fast, speak clearly, then prove it","Look impressive, sound busy, close hard","Greet warmly, chat a while, upsell everything","Collect an email, then follow up later"], why:"Speed to the door, a clear offer, proof it delivers: that's the whole job description."},
    {id:"q.p1.value-prop.a", c:["c.p1.value-prop"], q:"A windsurfer wants a homepage headline. Which one actually says what she sells and where?", a:["Custom windsurfing sails, built on Bonaire","Ride the wind, feel the freedom","Passion for performance drives everything we do","Welcome to our official company website"], why:"Clear beats clever, every time. Say what you sell, for whom."},
    {id:"q.p1.cta.a", c:["c.p1.cta"], q:"Your homepage has photos, story, everything, but no button telling people what to do next. What have you actually built?", a:["A pitch that never asks for the sale","A brochure, and that's perfectly fine","A safer bet, since pushing turns people off","A trust signal, showing you're not pushy"], why:"The call to action is the moment you ask for the sale. No ask, no sale."},
    {id:"q.p1.value-prop.b", c:["c.p1.value-prop"], q:"A rival business could paste your 'about us' paragraph onto their own site and nobody would notice. What does that tell you?", a:["It says nothing that's actually yours","It's too long for a homepage","It should mention a client by name","It needs one more specific number included"], why:"If a competitor could truthfully paste your sentence onto their site, it was never selling anything."},
    {id:"q.p1.friction.a", c:["c.p1.friction"], q:"Your visitor scrolls, squints, still can't tell which button does what. What does she do next?", a:["Taps back, since guessing takes effort","Reads every word twice to be sure","Emails you to ask what it means","Compares it carefully against three competitor sites first"], why:"Every unclear thing is a small tax. Strangers do not pay taxes for you."},
    {id:"q.p1.hero.a", c:["c.p1.hero"], q:"Someone lands on your homepage with one question in mind. What do they actually do with your words?", a:["Scan fast for the answer they need","Read every sentence carefully, start to finish","Compare your wording to three competitors first","Bookmark the page to read later tonight"], why:"They arrive with a question, glance for a few seconds, and either see the answer or leave."},
    {id:"q.p1.audit.a", c:["c.p1.audit"], use:"mastery", q:"A friend asks what you actually do when you 'audit' a website. What's the honest answer?", a:["Walk it like a customer, list what's costing her","Check every line of code carefully for hidden errors","Compare it to five competitor websites","Count how many pages it actually has"], why:"Speed, clarity, proof, in that order, with one line per problem and what it costs."},
    {id:"q.p1.choice-overload.a", c:["c.p1.choice-overload"], use:"mastery", q:"A service menu lists twelve options, all the same size, same weight. What happens to the visitor deciding?", a:["She closes the tab without picking any","She reads all twelve carefully first","She calls to ask which is cheapest","She picks whichever option is listed first"], why:"More options feels generous. It reads as work, and work gets put off forever."}
  ],
  translate: [
    {id:"t.p1.conversion.a", c:["c.p1.conversion"], setup:"A salon owner has never heard the word 'conversion'. Which explanation lands best?", a:["Ten people walk into your shop, one buys. Get two of ten, you doubled sales.","We optimize your conversion funnel to maximize visitor to customer throughput and revenue.","Conversion means turning site traffic into paying transactions using persuasive user experience design."], why:"The shop picture is felt in one second. The other two are heard and forgotten."},
    {id:"t.p1.salesperson.a", c:["c.p1.salesperson"], setup:"Explain what a website is for, with zero terminology.", a:["Picture a shop with a dusty window and a sticky door. We clean the window, oil the door.","A website is your digital storefront leveraging your brand presence across all channels.","A website is a twenty four seven omnichannel customer touchpoint across every single brand channel."], why:"The dusty window is instantly felt. Omnichannel touchpoint is instantly forgotten."},
    {id:"t.p1.proof.a", c:["c.p1.proof"], setup:"Explain social proof to someone who distrusts marketing talk.", a:["Two food stands sit side by side, one has a line. You join the line. Nobody told you to.","Social proof leverages herd psychology and social norms to reduce perceived risk in purchase decisions.","It's about building brand trust equity through client testimonials and reviews."], why:"The food stand line is proof explained by a human. The others sound like the marketers he already distrusts."},
    {id:"t.p1.fold.a", c:["c.p1.fold"], use:"mastery", setup:"Explain 'above the fold' to a shop owner who has never built a website.", a:["Everything they see before scrolling, like your window display, not the back room.","It's the visible viewport prior to any user scroll interaction occurring.","That's your primary above the fold real estate reserved for conversion optimization purposes."], why:"The window display lands instantly. The jargon versions explain nothing to someone who has never coded."}
  ],
  diagnose: [
    {id:"d.p1.conversion.a", c:["c.p1.conversion"], say:"'People visit my site but nobody books.'", a:["Conversion: speed, clarity or proof is broken","SEO: the site cannot be found by anyone searching","Branding: the logo needs updating"], why:"Visitors arriving means people can find you. Falling out between look and book is the money problem."},
    {id:"d.p1.credibility.a", c:["c.p1.credibility"], use:"mastery", say:"'Visitors tell me we look shady, even though we've been open for years.'", a:["Credibility: something reads as abandoned","SEO: the site needs a lot more backlinks","Pricing: your prices are set far too low"], why:"A copyright line stuck in some old year quietly tells every visitor the business might be gone."},
    {id:"d.p1.hero.a", c:["c.p1.hero"], use:"mastery", say:"'People land on my homepage and scroll straight past the top without pausing.'", a:["The hero: the first screen isn't selling","Analytics: you need better visitor tracking","Social media: you should post more often"], why:"The first screen is the whole shop window. If it doesn't sell, nothing below it gets read."}
  ]
},
{
  id: "p2", num: "P2", title: "Bottlenecks, Custom Software & AI", icon: "⚙️",
  read: "modules/reel-school-02.html",
  cards: [
    {id:"f.p2.bottleneck.a", c:["c.p2.bottleneck"], t:"Bottleneck", d:"The narrowest point everything must pass through; sets the speed of the whole business.", s:"the point where everything gets stuck"},
    {id:"f.p2.workflow.a", c:["c.p2.workflow"], t:"Workflow", d:"The steps a task goes through from start to done.", s:"how a job travels through your business"},
    {id:"f.p2.automation.a", c:["c.p2.automation"], t:"Automation", d:"Software following fixed rules: when this happens, do that.", s:"the boring stuff happens by itself"},
    {id:"f.p2.human-loop.a", c:["c.p2.human-loop"], t:"Human in the loop", d:"The system prepares, a person approves. Control stays with the human.", s:"the machine does the legwork, you keep the yes"},
    {id:"f.p2.integration.a", c:["c.p2.integration"], t:"Integration", d:"Two systems exchanging data automatically instead of via a human.", s:"your systems finally talk to each other"},
    {id:"f.p2.api.a", c:["c.p2.api"], t:"API", d:"The official plug a system offers so other software can connect to it.", s:"the plug that lets systems connect"},
    {id:"f.p2.single-source.a", c:["c.p2.single-source"], t:"Single source of truth", d:"One place where the real, current data lives; everything else reads from it.", s:"one list that is always right"},
    {id:"f.p2.saas.a", c:["c.p2.saas"], t:"Off-the-shelf / SaaS", d:"Ready-made subscription software, one-size-fits-most, paid monthly forever.", s:"ready-made, rented, fits nobody perfectly"},
    {id:"f.p2.custom-software.a", c:["c.p2.custom-software"], t:"Custom software", d:"Built for one business's exact way of working; owned, not rented.", s:"built around how you actually work"},
    {id:"f.p2.back-office.a", c:["c.p2.back-office"], t:"Back office", d:"The internal screens where the team manages bookings, customers, money.", s:"the control room behind your website"},
    {id:"f.p2.dashboard.a", c:["c.p2.dashboard"], t:"Dashboard", d:"One screen showing the state of the business at a glance.", s:"everything on one screen"},
    {id:"f.p2.process-map.a", c:["c.p2.process-map"], t:"Process mapping", d:"Writing down the repeated tasks and steps a business runs on.", s:"we list what you repeat every day"},
    {id:"f.p2.quick-win.a", c:["c.p2.quick-win"], t:"Quick win", d:"A small first automation delivered fast to prove value before bigger work.", s:"we fix one painful thing first, fast"},
    {id:"f.p2.scope.a", c:["c.p2.scope"], t:"Scope", d:"The agreed edge of a project: what is in, what is out.", s:"exactly what we will build, on paper"},
    {id:"f.p2.manual-entry.a", c:["c.p2.manual-entry"], t:"Manual entry", d:"A human typing data a machine already had. The root of double entry.", s:"typing the same thing twice"}
  ],
  quiz: [
    {id:"q.p2.phone-test.a", c:["c.p2.phone-test","c.p2.bottleneck"], q:"You ask a rental owner if he could switch his phone off for two weeks. He goes quiet, then admits no. What does that pause tell you?", a:["Everything runs through him","He just really loves his phone, honestly","He needs a proper phone plan upgrade","His whole team is probably unreliable"], why:"That is not dedication, it is a queue with a yearly bill attached."},
    {id:"q.p2.bottleneck-bill.a", c:["c.p2.bottleneck-bill"], q:"A client spends ten hours a week on admin, worth fifty euros an hour to her. What is the honest yearly cost of that?", a:["About twenty six thousand euros","About five hundred euros","Impossible to know without more data","Whatever a bookkeeper would charge"], why:"Hours times rate times fifty two. Nobody argues with their own numbers."},
    {id:"q.p2.automation.a", c:["c.p2.automation"], q:"A software quote leads with automation, and AI only gets a maybe-later mention. Why sequence it that way?", a:["Rules are cheaper and proven fast","AI is illegal in most countries","Automation is simply newer technology","Clients never actually want AI"], why:"Most businesses need reliable rules first, and rules show wins in week one."},
    {id:"q.p2.saas.a", c:["c.p2.saas"], q:"A hair salon plugin handles appointments fine. A scooter rental with deposits and damage waivers tries the same plugin. What happens?", a:["The business bends around its limits","It works exactly the same way","The plugin adds those features for free","Nothing, all booking software is identical"], why:"Ready-made software fits almost everyone reasonably well, which means it never quite fits you."},
    {id:"q.p2.human-loop.a", c:["c.p2.human-loop"], q:"A scooter rental owner gets every booking request as a phone notification. He taps once to approve. What is he keeping?", a:["The final yes, not the typing","Full control of the whole calendar","Extra work for himself, really","Nothing, the system decides alone"], why:"The machine does the legwork, the human keeps the approval. That is human in the loop."},
    {id:"q.p2.saas.b", c:["c.p2.saas","c.p2.custom-software"], q:"A boutique's booking process is identical to every other boutique's. A friend suggests building something custom. Good idea?", a:["No, standard process fits standard tools","Yes, custom always beats off-the-shelf, period","Only if she can really afford it","Only for businesses over five years old, apparently"], why:"Custom is for the part of a business that makes it different, not for the standard parts."},
    {id:"q.p2.manual-entry.a", c:["c.p2.manual-entry"], q:"A booking gets typed into WhatsApp, then the spreadsheet, then the invoice. Three separate times. What is that called?", a:["Manual entry","Good record keeping, actually","A sensible backup strategy, just in case","An integration between three separate systems"], why:"Every retype is a fresh chance for the wrong date or the wrong name."},
    {id:"q.p2.automation.b", c:["c.p2.automation"], q:"You tell a client 'you probably don't need AI yet.' She looks surprised, then relieved. Why does that line land so well?", a:["Everyone else sells hype, you didn't","It quietly lowers your asking price","AI is actually pretty useless for her","She prefers doing things by hand, mostly"], why:"The most trust-building sentence you own, because it costs you a sale you did not want."},
    {id:"q.p2.dashboard.a", c:["c.p2.dashboard"], use:"mastery", q:"Every morning you check WhatsApp, then a spreadsheet, then the bank app, just to know where today stands. What replaces all three checks with one?", a:["A dashboard","A bigger phone","A weekly meeting","A second employee"], why:"One screen showing the state of the business at a glance is exactly what a dashboard is for."},
    {id:"q.p2.scope.a", c:["c.p2.scope"], use:"mastery", q:"Halfway through the project, the client asks for a full site redesign that was never part of the deal. What should have prevented this argument?", a:["A written scope","A bigger deposit paid upfront","A longer, more detailed contract","A firmer tone of voice throughout"], why:"Write down what's in and what's out before work starts, so nobody is guessing later about what was actually promised."}
  ],
  translate: [
    {id:"t.p2.bottleneck.a", c:["c.p2.bottleneck"], setup:"Explain 'bottleneck' with zero business jargon.", a:["Picture a five-lane highway squeezing into one toll booth. The booth sets everyone's speed.","Your throughput is constrained by a single point of failure somewhere in your operational pipeline architecture.","It is a capacity limitation inherent to your current process architecture and resourcing model."], why:"The toll booth is felt in the stomach. 'Operational pipeline architecture' is heard and forgotten."},
    {id:"t.p2.automation.a", c:["c.p2.automation"], setup:"Explain automation versus AI at a kitchen table.", a:["Automation is a coffee machine: same button, same coffee. AI is a quick young helper who can read your mail.","Automation is deterministic rule execution, whereas AI relies on probabilistic inference over trained model weights.","Automation handles structured data workflows, while AI is built to handle unstructured, ambiguous data."], why:"The coffee machine and the young helper carry the whole distinction without one technical word."},
    {id:"t.p2.human-loop.a", c:["c.p2.human-loop"], setup:"A worried owner asks if the robot will talk nonsense to customers. Best answer?", a:["Nothing reaches a customer without your yes, like a chef who nods before any plate leaves the pass.","Modern large language models exhibit comparatively low hallucination rates under most published benchmarks.","We use guardrails, evaluation frameworks and continuous monitoring pipelines across the whole stack."], why:"The chef's nod answers the fear, not the technology. The other answers feed the fear."},
    {id:"t.p2.back-office.a", c:["c.p2.back-office"], use:"mastery", setup:"Explain 'back office' to an owner who has never heard the term.", a:["Think of it as the control room behind your website, the screens only your team sees.","It's the internal administrative interface layer sitting behind the customer-facing application.","That's your backend management console, essentially, for internal operational use only."], why:"The control room picture lands instantly. 'Administrative interface layer' explains nothing to someone who has never coded."}
  ],
  diagnose: [
    {id:"d.p2.bottleneck.a", c:["c.p2.bottleneck"], say:"'I am drowning in admin, my evenings are gone.'", a:["A bottleneck: manual work a system should do","A marketing problem needing more new customers","A branding problem needing a whole new logo"], why:"The 10 pm workload is a queue. Queues are bottleneck symptoms, and systems remove queues."},
    {id:"d.p2.automation.a", c:["c.p2.automation"], say:"'We want to do something with AI.'", a:["Automation first, find the repeated task","Buy an AI subscription immediately, today","Build a chatbot for the homepage, fast"], why:"The first question is never about AI. It is: what task do you repeat every single day?"},
    {id:"d.p2.bottleneck.b", c:["c.p2.bottleneck","c.p2.phone-test"], say:"'Everything runs through me personally.'", a:["He is the bottleneck","The team clearly needs some motivation training","The prices are probably set too low"], why:"Every booking, question and invoice squeezing through one person caps the whole business at that person's speed."},
    {id:"d.p2.api.a", c:["c.p2.api"], use:"mastery", say:"'Every morning I open the bank app just to see if yesterday's deposits actually came through.'", a:["No connection: the systems should tell each other","Banking problem: switch to a different bank","Discipline problem: check it before coffee instead"], why:"Payment providers already offer a plug for exactly this, called an API. Without it, the owner stays the messenger between two systems that could talk directly."},
    {id:"d.p2.workflow.a", c:["c.p2.workflow"], use:"mastery", say:"'Honestly, I don't even know every step between a booking coming in and the money actually landing.'", a:["Nobody has ever mapped the workflow","A staffing shortage, most likely","A pricing mistake somewhere along the line"], why:"You cannot fix or automate a path you have never written down. Mapping it first is free, and it's usually the first time anyone has seen it laid out."}
  ]
},
{
  id: "m1", num: "M1", title: "Website Building", icon: "🏗️",
  read: "modules/academy-module-1.html",
  cards: [
    {id:"f.m1.ux.a", c:["c.m1.ux"], t:"UX", d:"How easy it is for a visitor to do what they came for.", s:"how easy your site is to use"},
    {id:"f.m1.ui.a", c:["c.m1.ui"], t:"UI", d:"The visible layer: buttons, screens, colors.", s:"what it looks and feels like"},
    {id:"f.m1.seo.a", c:["c.m1.seo"], t:"SEO", d:"Earning a better spot in search results with words, trust and speed.", s:"being found when people search for what you sell"},
    {id:"f.m1.local-seo.a", c:["c.m1.local-seo"], t:"Local SEO", d:"The Google map box: Business Profile, reviews, photos, hours.", s:"the map result with your reviews"},
    {id:"f.m1.responsive.a", c:["c.m1.responsive"], t:"Responsive", d:"The site rearranges to work on every screen size.", s:"works perfectly on phones"},
    {id:"f.m1.cms.a", c:["c.m1.cms"], t:"CMS", d:"The dashboard for editing content without a developer.", s:"you can update it yourself"},
    {id:"f.m1.domain.a", c:["c.m1.domain"], t:"Domain", d:"The address: yourbusiness.com. Rented yearly, control matters.", s:"your address on the internet"},
    {id:"f.m1.hosting.a", c:["c.m1.hosting"], t:"Hosting", d:"The computer where the site lives; quality drives speed and uptime.", s:"where your site lives"},
    {id:"f.m1.frontend.a", c:["c.m1.frontend"], t:"Frontend", d:"Everything the visitor sees and touches.", s:"the part your customers see"},
    {id:"f.m1.backend.a", c:["c.m1.backend"], t:"Backend", d:"The machinery: processing, storage, logic behind the screens.", s:"the machinery behind it"},
    {id:"f.m1.https.a", c:["c.m1.https"], t:"HTTPS", d:"Encrypted connection; the padlock. Missing it triggers browser warnings.", s:"the padlock that says you are safe"},
    {id:"f.m1.analytics.a", c:["c.m1.analytics"], t:"Analytics", d:"Measurement of visits, sources and behavior.", s:"knowing what visitors actually do"},
    {id:"f.m1.landing-page.a", c:["c.m1.landing-page"], t:"Landing page", d:"A single page built for one audience and one action.", s:"one page, one goal"},
    {id:"f.m1.launch.a", c:["c.m1.launch"], t:"Launch", d:"The moment the site goes live on the real domain.", s:"the day it goes live"}
  ],
  quiz: [
    {id:"q.m1.ux.a", c:["c.m1.ux","c.m1.ui"], q:"Your customer says the site looks stunning, but she still can't find the book button after ten seconds. What actually broke?", a:["UX: looks great, still doesn't work","UI: the colors clash somewhere","SEO: she barely found the site","Hosting: the pages load slowly"], why:"UI is the look. UX is whether people can actually do the thing, and hers can't book yet."},
    {id:"q.m1.ui.a", c:["c.m1.ui"], q:"A client points at the blue button, the photo grid and the top menu, and asks what that whole visible layer is called.", a:["The UI","The UX","The backend","The domain"], why:"UI is the look: buttons, screens, colors. What you literally tap and see."},
    {id:"q.m1.local-seo.c", c:["c.m1.local-seo"], q:"A restaurant owner asks where to spend her one free afternoon on marketing this month. What pays off first?", a:["Fixing her Google Business Profile","A blog post about local food","More keywords on the homepage","Backlinks from the local newspaper"], why:"For a local business the map box brings in more customers than the rest of the site combined."},
    {id:"q.m1.seo.c", c:["c.m1.seo"], q:"A client wants SEO results by Friday. What do you actually tell her?", a:["It takes months, not days","Sure, I'll rank you by Monday","Only if we pay extra","Google decides that on Fridays"], why:"SEO is a garden, not a switch. Anyone promising instant rankings is selling something that gets punished later."},
    {id:"q.m1.domain.a", c:["c.m1.domain"], q:"An old web builder registered your domain under his own name. Now he wants five hundred euros to hand it back. What would have prevented this?", a:["Owning the domain from day one","A longer contract signed with him","Better SEO done from the start","A much cheaper hosting plan instead"], why:"Whoever controls the domain controls where visitors end up. The deed belongs in your drawer, not his."},
    {id:"q.m1.cms.a", c:["c.m1.cms"], q:"A client asks 'can I update it myself?' They are asking for...", a:["A CMS","A new domain","Better hosting","An SSL certificate"], why:"They just do not know the word. Your job is knowing it for them."},
    {id:"q.m1.frontend.a", c:["c.m1.frontend"], q:"The booking button on your customer's site turns the wrong color when tapped. Which layer are you fixing?", a:["The frontend: what she sees","The backend: the hidden logic","The domain: the site address","The hosting: the server itself"], why:"If something looks wrong to a visitor, it is almost always sitting right there in the frontend."},
    {id:"q.m1.analytics.a", c:["c.m1.analytics"], q:"A shop owner has a hunch that most visitors quit on the pricing page, but she's never actually checked. What settles it?", a:["Analytics: real numbers, not guesses","A much bigger ad budget","A brand new company logo","Just asking her regular customers"], why:"Analytics turns a guess into an answer. It might confirm her hunch, or show something else entirely."},
    {id:"q.m1.launch.a", c:["c.m1.launch"], q:"The new site has sat on a private preview link for a week, finished and approved. What actually still has to happen?", a:["Launch: moving it to the domain","One more design review meeting","A fresh, final round of testing","Renaming just a few pages"], why:"Launch is the day it goes live for real, where actual customers can find it."},
    {id:"q.m1.https.b", c:["c.m1.https"], use:"mastery", q:"A visitor never notices HTTPS is even there. What does that mean it's doing right?", a:["Working quietly, exactly as it should","Slowing the site down a little","Blocking most search engines","Making the design load faster"], why:"Good security is invisible until it's missing. The padlock only gets noticed when it's gone."},
    {id:"q.m1.hosting.b", c:["c.m1.hosting"], use:"mastery", q:"Two sites, same design, same photos. One loads in one second, one in six. What's the most likely difference?", a:["The quality of the hosting","The color of the logo","How old the domain is","The number of pages"], why:"Hosting is the land the site is built on. Cheap land shows up as a slow site, even when everything else is done well."}
  ],
  translate: [
    {id:"t.m1.seo.a", c:["c.m1.seo"], setup:"Explain SEO to someone who thinks it is a scam.", a:["Google is the phonebook now. We help it understand what you sell.","We optimize your on-page signals and authority metrics.","SEO is about ranking algorithms and keyword strategy."], why:"The phonebook needs no trust in marketing, just in phonebooks. The others sound exactly like the scam he fears."},
    {id:"t.m1.domain.a", c:["c.m1.domain"], setup:"Explain domain ownership with a picture, not a policy.", a:["Your address is the deed to your shop, kept in your hands.","We follow standard registrar practice with full credential handover to you.","You will receive administrator rights on the DNS configuration panel."], why:"The deed in the drawer makes an abstract risk physically felt."},
    {id:"t.m1.cms.a", c:["c.m1.cms"], setup:"Explain what a CMS gives the owner.", a:["Your own key: change prices and photos yourself, in minutes.","A headless content layer with a full editing interface.","Full CRUD access to your entire content database."], why:"The key to your own shop window says freedom. CRUD says nothing to anyone normal."},
    {id:"t.m1.responsive.a", c:["c.m1.responsive"], use:"mastery", setup:"Explain 'responsive' to an owner who has never heard the word.", a:["It stacks into one column on a phone, spreads out on a laptop.","The layout adapts fluidly across device breakpoints.","It's a fully fluid, mobile-first grid system."], why:"The stacking menu is felt in one glance. 'Fluid breakpoints' means nothing to someone who has never coded."}
  ],
  diagnose: [
    {id:"d.m1.seo.a", c:["c.m1.seo"], say:"'We're a brand new business. Nobody has ever heard of us online.'", a:["Findability: no SEO or Google presence","Conversion: the whole site is losing visitors","Branding: the outdated logo needs real work"], why:"Nobody finding you and visitors not booking are two completely different money problems. Start with whether they can find you at all."},
    {id:"d.m1.cms.a", c:["c.m1.cms"], say:"'If I want one sentence changed on my site, I have to email a guy and wait two weeks.'", a:["No CMS: can't touch her own site","Bad SEO: the site needs more keywords","She probably needs a whole new website"], why:"Going through someone else is the whole problem in one sentence. A CMS hands the keys back."},
    {id:"d.m1.analytics.a", c:["c.m1.analytics"], say:"'Bookings just went up last month. I have no idea why, so I can't repeat it.'", a:["Analytics: nobody's tracking what visitors do","Pricing: she should raise her prices","Hosting: the server probably got faster"], why:"Without analytics, even a win is a mystery. Knowing what changed is the only way to repeat it."},
    {id:"d.m1.landing-page.a", c:["c.m1.landing-page"], use:"mastery", say:"'We ran an ad, but it just sent people to our busy homepage full of everything.'", a:["Missing landing page: too many distractions","Bad ad creative, needs a redesign","Wrong platform for the ad"], why:"A landing page exists so ad clickers see exactly the offer, with nothing else pulling them away."}
  ]
},
{
  id: "m2", num: "M2", title: "Branding & Positioning", icon: "🧭",
  read: "modules/academy-module-2.html",
  cards: [
    {t:"Brand", d:"The sum of what people think and say about a business.", s:"what people say when you are not in the room"},
    {t:"Positioning", d:"The chosen slot in the customer's head: for whom, different how.", s:"the slot you own in people's heads"},
    {t:"Differentiator", d:"A claim competitors cannot truthfully copy.", s:"the thing only you can say"},
    {t:"Niche", d:"The deliberately narrowed audience or specialty.", s:"who you are really for"},
    {t:"Messaging", d:"The repeated core sentences: what, for whom, why you.", s:"the words you repeat everywhere"},
    {t:"Tone of voice", d:"The personality of the words: formal, warm, playful, direct.", s:"how your business sounds"},
    {t:"Visual identity", d:"The recognition system: logo, colors, type, photo style.", s:"your recognizable look"},
    {t:"Brand kit", d:"The rulebook for applying the identity consistently.", s:"the rulebook so everything matches"},
    {t:"Perceived value", d:"What people assume you cost before seeing the price.", s:"what you look like you cost"},
    {t:"Touchpoint", d:"Any place a customer meets the brand: site, socials, invoice, van.", s:"everywhere a customer meets you"},
    {t:"Rebrand", d:"Deliberately changing the positioning and identity, not just the logo.", s:"changing what you stand for, not just the logo"},
    {t:"Target audience", d:"The specific group the brand is built to attract.", s:"your ideal customer"}
  ],
  quiz: [
    {q:"Customers always haggling on price is a symptom of...", a:["A positioning problem: they look interchangeable","A price problem: too expensive","A website problem: too slow","A staffing problem"], why:"Interchangeable things get compared on price only. Nobody haggles with the specialist."},
    {q:"Why does 'for everyone' fail as positioning?", a:["Human memory stores one slot per business; 'for everyone' reads as 'nothing special'","It is illegal to exclude customers","Niches are always richer","Google penalizes broad websites"], why:"If you do not choose your slot, the market assigns you 'one of the others', the most expensive slot there is."},
    {q:"'Narrow the message, not the door' means...", a:["Be clearly for someone; everyone else still comes, on your terms","Close your shop to walk-ins","Only serve one customer type ever","Make the website smaller"], why:"The wedding photographer gets family shoots too. Being clearly for someone signals competence to all."},
    {q:"A differentiator must pass which test?", a:["The copy-paste test: a competitor could not truthfully claim it","The billboard test: it fits on a sign","The slogan test: it rhymes","The budget test: it costs under 1000"], why:"'Quality and service' fails for everyone. 'Every booking confirmed within a minute, day or night' passes."},
    {q:"The difference between a logo and a brand is...", a:["The logo is the flag, the brand is the country","They are the same","The logo is more important","The brand is just the color palette"], why:"Redesigning the flag does not change the country, which is why logo-only rebrands change nothing customers feel."},
    {q:"Why does consistency beat brilliance?", a:["Trust is built by repetition, and every inconsistency resets the counter","Brilliant designs are expensive","Customers dislike creativity","Consistency is easier to invoice"], why:"A decent identity applied everywhere outperforms a beautiful one applied randomly."},
    {q:"'People do not price-shop the specialist, they price-shop the...'", a:["generic","expensive","local","famous"], why:"When a business looks like every other, price is the only thing left to compare."},
    {q:"The sail maker's site is nearly empty: logo, one sentence, one contact button. Why does that work?", a:["Positioning as subtraction: a craft brand needs one unmistakable sentence, not ten pages","The builder ran out of time","Empty sites load faster for SEO","It saves hosting costs"], why:"Confidence is quiet. Insecurity is ten menu items."},
    {q:"Good messaging starts sentences with...", a:["The customer's situation, not with 'we'","The company mission","The founding year","An inspiring quote"], why:"'Your scooter is confirmed before you finish your coffee' beats 'we are passionate about quality'."},
    {q:"Raising perceived value instead of lowering prices is smart because...", a:["It is often cheaper and it compounds; discounts do neither","Customers never notice prices","Premium looks are free","Low prices are illegal in some markets"], why:"The label decides what people expect to pay before the offer is read."}
  ],
  translate: [
    {setup:"Explain positioning at a kitchen table.", a:["Five fruit stands on the market square, but everyone knows 'the one with the sweet mangoes'. People walk past four stands for it. Your business needs its mango.","Positioning is your differentiated place in the competitive landscape.","It is about owning mental real estate in your category."], why:"The mango stand is a story people retell. 'Mental real estate' is a phrase people escape from."},
    {setup:"Explain perceived value without saying 'perceived value'.", a:["Same wine, two labels: one beautiful, one a printed sticker. People pay more for the first and swear it tastes better. Your business has a label too.","Your price elasticity is influenced by presentation quality signals.","Premium aesthetics increase willingness-to-pay."], why:"The wine bottle does in ten seconds what the jargon versions never do."},
    {setup:"Explain why consistency matters, plainly.", a:["You trust your favorite bar because it feels the same every visit. Different music, prices and name each time, and you would stop going without knowing why.","Inconsistent touchpoints erode brand equity accumulation.","Consistency drives recognition metrics."], why:"The bar you would quietly stop visiting is consistency explained from the inside."}
  ],
  diagnose: [
    {say:"'People do not really get what we do.'", a:["Messaging: the words are vague, clever, or about themselves","Visual identity: the logo is weak","Systems: no booking flow"], why:"The offer needs to survive one plain sentence. If customers cannot repeat it, it does not exist."},
    {say:"'We look cheaper than we are.'", a:["Perceived value: the visuals discount the price before it is read","SEO: not enough keywords","Bottleneck: too much admin"], why:"Dated visuals write a discount on the label. Raising the look is pricing power."},
    {say:"'We look different everywhere: sign, site, Instagram.'", a:["Consistency: recognition never accumulates, trust never compounds","Positioning: wrong niche","Conversion: weak call to action"], why:"Three first impressions, zero compound interest. One system, applied everywhere, fixes it."},
    {say:"'We attract bargain hunters and the wrong kind of customers.'", a:["Positioning: the brand signals broadcast to everyone, so everyone shows up","Advertising: wrong ad budget","Hosting: site too slow"], why:"Broadcast to everyone and the bargain hunters answer loudest. Choose who it is for."}
  ]
}
];
