/* Salty Academy data · open-answer and matching items. Task 13 fills in the rest. */
window.ACADEMY_OPEN = {
  p1: [
    { id:"o.p1.speed.a", c:["c.p1.speed"], use:"module",
      ask:"A cafe owner says her site is fine, it just takes a few seconds. What do you tell her?",
      rubric:{ must:[["slow","seconds","speed","load"],["leave","lose","gone","bounce","back"]],
               nice:[["never","silent","complain","tell you"]],
               miss:[{ match:["google","ranking","seo"],
                       say:"Speed does affect ranking, but the money problem is the visitor who left before the page appeared." }],
               minMust:1 },
      model:"Three seconds of blank screen feels the same as a broken site. Most phone visitors leave, and none of them complain, so she never hears about it.",
      why:"The point is the silence: she cannot see the customers she lost." },
    { id:"o.p1.value-prop.a", c:["c.p1.value-prop"], use:"module",
      ask:"A client's homepage says 'We are passionate about quality and service.' What do you actually tell her?",
      rubric:{ must:[["generic","vague","meaningless","interchangeable","competitor","anybody"],
                      ["specific","concrete","unique","specialize","different","details"]],
               nice:[["rival","competitor","truthfully","identical"]],
               miss:[{ match:["stronger","better","impressive","exciting"],
                       say:"Adding stronger adjectives does not fix it. It still needs to say something no competitor could truthfully claim." }] },
      model:"That line could sit on any competitor's homepage and nobody would notice, so it isn't actually selling anything. Replace it with the one specific thing only this business can truthfully say, like exactly how fast a booking gets confirmed.",
      why:"The copy-paste test: if a rival could paste it onto their own site, it proves nothing." },
    { id:"o.p1.friction.a", c:["c.p1.friction"], use:"mastery",
      ask:"A rental booking form asks for a company name, a job title and a referral source before the date. What's actually happening here?",
      rubric:{ must:[["unnecessary","irrelevant","pointless","overkill","excessive"],
                      ["abandon","hesitate","frustrated","reconsider","disappear"]],
               nice:[["strip","simplify","remove","shorten"]],
               miss:[{ match:["information","details","understand","useful"],
                       say:"More fields do not mean better leads. They mean fewer people finish the form at all." }] },
      model:"Every extra field the visitor doesn't need is a reason to stop and think, and thinking is exactly what a rushed visitor won't do. Strip the form down to the date and a way to reach them, and more people will actually finish booking.",
      why:"Every extra tap costs you a slice of the people who were already ready to book." },
    { id:"x.p1.value-prop.a", c:["c.p1.value-prop","c.p1.speed","c.p1.choice-overload","c.p1.proof"], use:"module",
      ask:"Match each complaint to the real problem behind it.",
      pairs:[ {l:"'I can't tell what she actually sells'", r:"A weak value proposition"},
              {l:"'The page took forever, I gave up'", r:"A slow load time"},
              {l:"'There were three buttons, I picked none'", r:"Choice overload"},
              {l:"'It looked fine but had no reviews anywhere'", r:"Missing social proof"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." }
  ],
  p2: [
    { id:"o.p2.bottleneck-bill.a", c:["c.p2.bottleneck-bill"], use:"module",
      ask:"A client says her admin doesn't really cost her anything, she does it herself for free. How do you show her what it actually costs?",
      rubric:{ must:[["hours","multiply","calculate","fifty-two","do the math"],
                      ["yearly","forever","ongoing","recurring","adds up"]],
               nice:[["real number","concrete","specific","her own numbers"]],
               miss:[{ match:["expensive","costly","pricey"],
                       say:"Saying it's expensive isn't the same as running the actual numbers. The formula, not the adjective, is what convinces her." }] },
      model:"You do the math with her own numbers: hours spent each week times what her hour is worth times fifty two weeks, which turns ten hours into a real yearly figure like twenty six thousand euros. That number keeps repeating every year until the bottleneck is fixed, and nobody argues with their own numbers.",
      why:"The bottleneck bill turns a vague feeling of busyness into a number a client can't unsee." },
    { id:"o.p2.phone-test.a", c:["c.p2.phone-test"], use:"module",
      ask:"An owner insists everything runs fine because he personally handles it all. What question actually gets him to feel the problem?",
      rubric:{ must:[["unreachable","disconnect","offline","switch off","two weeks"],
                      ["bottleneck","dependent","reliant","without him","stuck point"]],
               nice:[["watch his face","pause","honest answer"]],
               miss:[{ match:["hire","staff","employee","assistant"],
                       say:"Hiring might eventually help, but the question is about proving he's the single point everything squeezes through, not about staffing yet." }] },
      model:"You ask if he could switch his phone off for two weeks and come back to a business that ran completely normally. Watch his face when he answers: if every booking and question squeezes through him, that isn't dedication, it's a queue with a yearly bill attached.",
      why:"The phone test turns an abstract idea into a question the owner has to answer about his own life." },
    { id:"x.p2.bottleneck.a", c:["c.p2.bottleneck","c.p2.workflow"], use:"module",
      ask:"Match each complaint to what is actually broken.",
      pairs:[ {l:"'I retype every booking into the calendar'", r:"Manual entry"},
              {l:"'Nobody knows which list is current'", r:"No single source of truth"},
              {l:"'It only jams on Saturdays'", r:"A bottleneck"} ],
      why:"Each complaint names a symptom, and the match is the real fault behind it." },
    { id:"o.p2.process-map.a", c:["c.p2.process-map"], use:"mastery",
      ask:"Before you write a single line of code for a new client, what's the actual first deliverable, and why does handing it over first matter?",
      rubric:{ must:[["write down","list","document","mapping","step by step"],
                      ["no cost","before building anything","earns trust","first time anyone"]],
               miss:[{ match:["price","quote","proposal","cost estimate"],
                       say:"A price isn't the first deliverable. The first thing is writing down how the business actually works today, before any number is discussed." }] },
      model:"Before building anything we sit down and write out exactly what the business repeats every day, step by step, including the WhatsApp back and forth. Handing that list over first costs nothing, and it's often the first time anyone has ever seen their own workflow on paper, which is what earns the trust to build the bigger thing.",
      why:"Process mapping is free, and it's usually the first time an owner has ever seen their own business written down." }
  ],
  m1: [
    { id:"o.m1.cms.a", c:["c.m1.cms"], use:"module",
      ask:"A client asks why she should care about having a CMS. What do you tell her?",
      rubric:{ must:[["herself","yourself","independently","directly","alone"],
                      ["developer","waiting","depend","stuck","someone"]],
               nice:[["minutes","password","login"]],
               miss:[{ match:["design","template","pretty","looks"],
                       say:"A CMS isn't about how the site looks, it's about who can change it and how fast." }] },
      model:"A CMS means she can log in and change a price or swap a photo herself, in minutes, instead of emailing a developer and waiting days. It's her own key to her own site, so day to day changes stop depending on someone else.",
      why:"The whole point of a CMS is independence: she stops needing to go through someone else for small changes." },
    { id:"o.m1.seo.a", c:["c.m1.seo"], use:"module",
      ask:"A client asks what SEO actually is, in plain words. What do you say?",
      rubric:{ must:[["ranking","showing","search","google","found"],
                      ["months","gradual","patience","ongoing","compounds"]],
               nice:[["clear","trust","fast"]],
               miss:[{ match:["trick","switch","guarantee","instant","overnight"],
                       say:"SEO isn't a trick you flip on. It's making the site genuinely clear and fast, and letting that compound over months." }] },
      model:"SEO is making sure Google understands what you sell and shows you to the people already searching for it. It isn't instant, and nobody can honestly guarantee a ranking, it takes months and keeps compounding the longer you stick with it.",
      why:"The point is killing two myths at once: SEO is not a trick, and it is not fast." },
    { id:"x.m1.cms.a", c:["c.m1.cms","c.m1.domain","c.m1.https","c.m1.responsive"], use:"module",
      ask:"Match each client complaint to the real problem behind it.",
      pairs:[ {l:"'I have to email someone to fix a typo'", r:"No CMS"},
              {l:"'A builder we can't reach still owns our address'", r:"No domain ownership"},
              {l:"'The browser says Not secure'", r:"Missing HTTPS"},
              {l:"'It looks perfect, except on a phone'", r:"Not responsive"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." },
    { id:"o.m1.analytics.a", c:["c.m1.analytics"], use:"mastery",
      ask:"An owner says her gut tells her most visitors come from Instagram, not Google. How do you actually find out if she's right?",
      rubric:{ must:[["analytics","numbers","tracking","measure","figures"],
                      ["sources","traffic","referral","visitors","origin"]],
               miss:[{ match:["instagram","assume","guess","probably"],
                       say:"Guessing which platform wins isn't the same as checking. Analytics shows the real traffic sources, not just the loudest one." }] },
      model:"You check her actual analytics instead of trusting a gut feeling, because it shows exactly where each visitor came from. It might confirm Instagram, or it might reveal Google was quietly doing more work the whole time.",
      why:"Analytics replaces a guess with a number. Gut feelings about traffic sources are wrong more often than owners expect." },
    { id:"o.m1.frontend.a", c:["c.m1.frontend","c.m1.backend"], use:"mastery",
      ask:"A client asks what 'frontend' and 'backend' actually mean, without any jargon. What's the plain answer?",
      rubric:{ must:[["visible","screens","buttons","customers","looks"],
                      ["hidden","machinery","behind","logic","invisible"]],
               miss:[{ match:["coding","programming","technical","complicated"],
                       say:"It's not really about how technical each part is, it's about whether a customer can see it or not." }] },
      model:"The frontend is everything a visitor actually sees and taps, the pages, the buttons, the photos. The backend is the hidden machinery behind it, the part that processes things and makes the visible part actually work, even though customers never see it directly.",
      why:"Frontend and backend split on one line: can a customer see it, or not." }
  ],
  m2: [
    { id:"o.m2.positioning.a", c:["c.m2.positioning"], use:"module",
      ask:"A client says customers always haggle over her price. What's actually going on?",
      rubric:{ must:[["positioning","interchangeable","swappable","replaceable","identical"],
                      ["compare","comparing","competing","differentiate","price"]],
               nice:[["specialist","memorable","choose","niche"]],
               miss:[{ match:["pricing","cheaper","discount","lower"],
                       say:"Lowering the price doesn't fix it. She needs to look less interchangeable, not less expensive." }] },
      model:"It's rarely a pricing problem. When a business looks just like every other option, price is the only thing left to compare, so people haggle. Fix what makes her different and the haggling usually quiets down.",
      why:"Haggling is a positioning symptom wearing a price complaint's clothes." },
    { id:"o.m2.perceived-value.a", c:["c.m2.perceived-value"], use:"module",
      ask:"A boutique owner wants to discount 20% to bring in more customers. What do you tell her before she touches the price?",
      rubric:{ must:[["perceived","looks","appears","presentation","premium"],
                      ["expensive","cheap","signal","trust","risky"]],
               nice:[["compounds","lasting","raise","upgrade"]],
               miss:[{ match:["compete","match","lower","matching"],
                       say:"Matching a competitor's price doesn't fix this. It's the look and presentation setting the expected price, not the number itself." }] },
      model:"People decide what something probably costs before they even read the price, based purely on how it looks. A sudden discount can actually signal something is wrong or cheap, so raising how premium it looks is often the smarter, cheaper move, and it keeps paying off.",
      why:"Perceived value means the look sets the expected price before anyone reads it." },
    { id:"x.m2.messaging.a", c:["c.m2.messaging","c.m2.perceived-value","c.m2.touchpoint","c.m2.audience"], use:"module",
      ask:"Match each complaint to the real problem behind it.",
      pairs:[ {l:"'People do not really get what we do'", r:"Vague messaging"},
              {l:"'We look cheaper than we actually are'", r:"Low perceived value"},
              {l:"'Our sign, site and Instagram all look different'", r:"Inconsistent touchpoints"},
              {l:"'We only attract bargain hunters'", r:"Wrong target audience"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." },
    { id:"o.m2.touchpoint.a", c:["c.m2.touchpoint"], use:"mastery",
      ask:"A client's van, invoices and website all use a slightly different blue and a different font. Why does that actually cost her something?",
      rubric:{ must:[["recognize","recognition","familiar","remember","notice"],
                      ["reset","restart","undermine","weaken","erode"]],
               nice:[["repetition","compound","builds","consistent"]],
               miss:[{ match:["design","pretty","stylish","tasteful"],
                       say:"It's not about which version looks nicer. It's that nothing repeats long enough for people to recognize it." }] },
      model:"Every touchpoint that looks slightly different makes a customer mentally start over, so recognition never has a chance to build. Matching the blue and the font everywhere is what turns repeated exposure into actual trust.",
      why:"Touchpoints only compound trust when they repeat. A mismatch resets the counter every time." }
  ],
  m3: [
    { id:"o.m3.funnel.a", c:["c.m3.funnel"], use:"module",
      ask:"A shop owner says her Instagram gets plenty of likes but almost no sales. How does the funnel explain what's actually happening?",
      rubric:{ must:[["pipeline","funnel","stages","narrowing"],
                      ["engagement","applause","attention","audience"],
                      ["leads","booking","conversion","customers"]],
               nice:[["raise their hand","a way to reach them","get in touch","follow up later"]],
               miss:[{ match:["reach","algorithm","hashtags","more posts"],
                       say:"More reach or more posts won't fix this. The likes prove people already see it, the leak sits later in the pipeline, where interest should turn into a raised hand." }] },
      model:"Likes happen early in the pipeline, when a stranger notices you, but a sale only happens several stages later, after someone becomes a lead and then a customer. Plenty of attention with no bookings usually means the leak is further down, like no clear next step or no follow up when someone actually shows interest.",
      why:"The funnel names the gap: a business can look great at the top, reach and likes, and still leak everything before an actual booking." },
    { id:"o.m3.garden-faucet.a", c:["c.m3.garden-faucet","c.m3.organic","c.m3.paid"], use:"module",
      ask:"A cafe owner asks why you'd ever recommend both paid ads and organic content when one is clearly more work. What do you tell her?",
      rubric:{ must:[["instant","immediate","faucet","turns off","stops paying"],
                      ["compounds","builds","garden","grows","keeps working"]],
               nice:[["months","weeks","sleep","forever"]],
               miss:[{ match:["cheaper","expensive","waste"],
                       say:"It's not about which one is cheaper. Ads and content solve two different timing problems, one fast and temporary, the other slow and lasting." }] },
      model:"Paid ads are the faucet, turn it on and bookings can show up within hours, but the moment you stop paying, the flow stops completely. Organic content is the garden, it takes months to grow, but once it's planted it keeps bringing customers even on days you post nothing. Most small businesses actually need both, the faucet while the garden is still growing.",
      why:"The garden and the faucet is the whole argument for not picking just one channel, they solve completely different timing problems." },
    { id:"x.m3.reach.a", c:["c.m3.reach","c.m3.engagement","c.m3.paid","c.m3.organic"], use:"module",
      ask:"Match each complaint to what's actually happening.",
      pairs:[ {l:"'Two thousand people saw the reel, nobody messaged'", r:"Reach without engagement"},
              {l:"'Four hundred likes and not one booking'", r:"Engagement without conversion"},
              {l:"'Bookings stopped the day the ad budget ran out'", r:"Paid reach, the faucet"},
              {l:"'Reviews from last year still bring in bookings'", r:"Organic reach, the garden"} ],
      why:"Each complaint names a symptom. The match is the real mechanic sitting underneath it." },
    { id:"o.m3.acquisition.a", c:["c.m3.acquisition"], use:"mastery",
      ask:"A client spent two hundred euros on ads and landed five new customers. She asks if that's actually a good number. What do you need to know first?",
      rubric:{ must:[["worth","value","lifetime","spend back"],
                      ["customer","repeat","return","comes back"]],
               nice:[["compare","forty euros","per customer"]],
               miss:[{ match:["cheap","expensive","decent","terrible"],
                       say:"Whether forty euros per customer is cheap or expensive isn't a guess, it depends entirely on what that customer is actually worth over time." }] },
      model:"Forty euros to win one customer only means something once you compare it to what that customer is worth, especially if she comes back and books again. A cheap looking number can still lose money, and an expensive looking one can still be a bargain.",
      why:"Acquisition cost only makes sense next to what a customer is worth, not on its own." },
    { id:"o.m3.creative.a", c:["c.m3.creative"], use:"mastery",
      ask:"Two ads run with identical targeting and identical budget. One books out the weekend, the other gets nothing. What's actually different?",
      rubric:{ must:[["creative","image","video","the ad itself"],
                      ["stops the scroll","grabs attention","catches the eye","stands out"]],
               nice:[["words","caption","photo"]],
               miss:[{ match:["targeting","algorithm","platform","luck"],
                       say:"Targeting and budget are already identical here, so neither one explains the gap. What's left different is the ad people actually see." }] },
      model:"With targeting and budget already the same, the only thing left that can differ is the creative itself, the actual image or video and the words attached to it. One ad stops the scroll and earns the tap, the other gets scrolled straight past, even to the exact same audience.",
      why:"Perfect targeting still can't save a boring creative. The ad people actually see is doing real work." }
  ],
  m4: [
    { id:"o.m4.fast-junior.a", c:["c.m4.fast-junior"], use:"module",
      ask:"A shop owner is amazed her new AI tool answers instantly, day or night. What's the honest way to think about what she's actually got?",
      rubric:{ must:[["quickly","instantly","tireless","nonstop","never tired","always available"],
                      ["confidently","mistakes","incorrect","double-check","review","verify"]],
               nice:[["junior","employee","onboarded","manage it"]],
               miss:[{ match:["thinks","brain","human","understands"],
                       say:"It doesn't think or reason like a person, it's just fast at producing text, which is exactly why someone still checks it." }] },
      model:"Think of it as a very fast junior assistant with endless patience, it can draft things instantly and never gets tired. But it's wrong with exactly the same confidence as it's right, so someone always checks the work before it reaches a customer.",
      why:"The fast junior model answers the amazement and the worry in the same breath: impressive speed, but no judgment of its own." },
    { id:"o.m4.hallucination.a", c:["c.m4.hallucination"], use:"module",
      ask:"Your AI chatbot confidently tells a customer you're open until midnight. You're actually closed at nine. What just happened, and what does it mean for how you use the tool?",
      rubric:{ must:[["confident","confidently","sounds true","plausible","made up","invented"],
                      ["review","checked","approve","human","double-check","verify"]],
               nice:[["ships","reaches a customer","before it goes out"]],
               miss:[{ match:["glitch","crashed","malfunction","broken"],
                       say:"It's not a bug or a crash, it's the model sounding confident about something it simply doesn't know, which a software fix alone won't cure." }] },
      model:"It hallucinated, it produced a confident, plausible-sounding answer that simply wasn't true. That's exactly why nothing customer-facing should go out without a person reviewing it first, especially the facts it states with total confidence.",
      why:"Confident and true are not the same thing. The fix isn't a smarter model, it's a human keeping the yes." },
    { id:"x.m4.llm.a", c:["c.m4.llm","c.m4.prompt","c.m4.context","c.m4.grounding"], use:"module",
      ask:"Match each moment to the AI idea behind it.",
      pairs:[ {l:"'It already writes like a pro, but knows nothing about my shop'", r:"The model itself"},
              {l:"'Vague instructions get vague answers back'", r:"A weak prompt"},
              {l:"'Paste last month's price list in first'", r:"Feeding it context"},
              {l:"'Connect it to your real prices so it stops guessing'", r:"Grounding"} ],
      why:"Each moment names a symptom. The match is the actual idea sitting underneath it." },
    { id:"o.m4.grounding.a", c:["c.m4.grounding","c.m4.context"], use:"mastery",
      ask:"A rep tells a client 'once we ground the AI in your data, it stops guessing.' The client asks what that actually means in plain terms. What do you tell her?",
      rubric:{ must:[["prices","numbers","actual","specific","real information"],
                      ["guessing","generic","accurate","quoting","stops guessing"]],
               miss:[{ match:["smarter","upgrade","bigger model","better version"],
                       say:"It's not about a smarter or upgraded model, it's simply teaching this one your actual numbers instead of the internet's." }] },
      model:"Grounding just means teaching it your actual prices and rules instead of letting it guess at what's typical for the industry. Once it can see your real numbers, it stops inventing plausible-sounding answers and starts quoting your business specifically.",
      why:"Grounding is the plain-English fix for generic answers: feed it the truth, and it stops guessing." },
    { id:"o.m4.training.a", c:["c.m4.training"], use:"mastery",
      ask:"A client assumes the AI 'knows' her business already, since it sounds so confident. What do you explain about how it actually learned what it knows?",
      rubric:{ must:[["patterns","general text","the internet","before it met you","learned already"],
                      ["fixed","doesn't update","stays the same","never met your business","has to be taught"]],
               miss:[{ match:["updates itself","keeps learning","gets smarter over time"],
                       say:"It doesn't quietly keep learning about her business on its own, everything specific still has to be taught to it directly." }] },
      model:"It learned general writing and reasoning patterns from a huge pile of text, long before it ever heard of her business. That learning is fixed at build time, so anything specific to her, like her prices or her tone, still has to be taught to it every time, it doesn't just pick it up on its own.",
      why:"Training is what it learned in school. Everything about this specific business still has to be taught." }
  ],
  m5: [
    { id:"o.m5.three-layers.a", c:["c.m5.three-layers"], use:"module",
      ask:"A client says her business 'just feels chaotic' lately, though she can't point to one specific thing that's broken. How do you find out what's actually wrong?",
      rubric:{ must:[["storage","database","records","filing","housed"],
                      ["rules","logic","backend","engine","process","automatic"],
                      ["screens","touch","interface","visible","frontend","dashboard"]],
               nice:[["missing","doubled","broken","disagree","conflict"]],
               miss:[{ match:["software","technology","computers","internet"],
                       say:"Naming 'the software' isn't specific enough yet. The real question is which of the three layers, data, rules or screens, is missing or doubled." }] },
      model:"Every piece of business software is really three layers: a place where the data lives, rules that move it around, and the screens people touch on top. When something feels chaotic without an obvious cause, it's almost always because one of those three layers is missing entirely or quietly duplicated somewhere else.",
      why:"The three layers give her one map to check almost any systems complaint against." },
    { id:"o.m5.database.a", c:["c.m5.database"], use:"module",
      ask:"A client asks why she needs 'a real database' instead of the shared spreadsheet her team has used for years. What's the honest answer?",
      rubric:{ must:[["trust","careful","typing","manual","mistake","unprotected"],
                      ["enforce","require","reject","structure","consistent","validate"]],
               nice:[["refuse","booking","double","overwrite","conflict"]],
               miss:[{ match:["expensive","complicated","technical","overkill"],
                       say:"It's not really about cost or complexity, it's about whether the mistake is even possible to make in the first place." }] },
      model:"A shared spreadsheet trusts every person typing into it to be careful every single time, and eventually somebody isn't. A real database enforces its own rules, so it simply refuses to save a booking that's missing a date or double books the same scooter, instead of hoping nobody ever makes that mistake.",
      why:"The database concept lands the moment she sees it's not about looks, it's about which mistakes are even possible." },
    { id:"x.m5.backend.a", c:["c.m5.backend","c.m5.webhook","c.m5.api","c.m5.back-office"], use:"module",
      ask:"Match each complaint to what's actually missing.",
      pairs:[ {l:"'The confirmation email just never goes out'", r:"No backend rule watching for it"},
              {l:"'We refresh the bank app every hour hoping to see the deposit'", r:"No webhook"},
              {l:"'This booking tool has no way for other software to plug in'", r:"No API"},
              {l:"'The form looks perfect, but nobody built a screen for staff to manage it'", r:"No back office"} ],
      why:"Each complaint names a symptom. The match is the real gap sitting underneath it." },
    { id:"o.m5.backend.a", c:["c.m5.backend"], use:"mastery",
      ask:"A booking confirmation email fires the second a payment lands, with nobody clicking send. What layer of the system is actually doing that work, and why does it matter that it's invisible?",
      rubric:{ must:[["backend","rules","logic","automatic","triggered","fires"],
                      ["invisible","hidden","unseen","nobody","without","behind"]],
               nice:[["reliable","consistent","trust","depend"]],
               miss:[{ match:["magic","coincidence","miracle","randomly"],
                       say:"It's not magic or a coincidence, it's a rule sitting in the backend that reacts the instant the payment event happens." }] },
      model:"That's the backend at work, the rules layer sitting behind the scenes that reacts the instant a payment event happens, without anyone clicking anything. It matters that it's invisible because customers only ever feel whether it works, they never see the machinery that gets the confirmation into their inbox.",
      why:"The backend never shows up on a screen, but every reliable moment like that one is backend logic doing its job quietly." },
    { id:"o.m5.frontend.a", c:["c.m5.frontend"], use:"mastery",
      ask:"A rental company's team keeps asking for 'a whole separate system' just for staff. What do you actually build them instead, and why?",
      rubric:{ must:[["screens","frontend","dashboard","interface","display"],
                      ["shared","underlying","connected","identical","single"]],
               nice:[["staff","customers","audience"]],
               miss:[{ match:["separate","standalone","independent","another"],
                       say:"It doesn't need to be a whole separate system. It's usually just another set of screens, the same frontend, reading the same underlying data a different audience needs to see." }] },
      model:"You don't build a second system, you build another set of screens, the same frontend pattern, reading and writing the same underlying data with a view built for staff instead of customers. It matters because two separate systems drift apart the moment someone forgets to update both of them.",
      why:"The frontend is just the part people touch, and staff screens are usually the other half of the same frontend, not a whole new build." }
  ]
};
