// Salty Academy game data · part 2 (M3, M4, M5, M6)
window.ACADEMY_PART2 = [
{
  id: "m3", num: "M3", title: "Growth & Marketing", icon: "📈",
  read: "modules/academy-module-3.html",
  cards: [
    {id:"f.m3.funnel.a", c:["c.m3.funnel"], t:"Funnel", d:"The pipeline: strangers, visitors, leads, customers, each stage smaller.", s:"the path from stranger to customer"},
    {id:"f.m3.lead.a", c:["c.m3.lead"], t:"Lead", d:"A person who raised a hand and left a contact route.", s:"someone who raised their hand"},
    {id:"f.m3.lead-magnet.a", c:["c.m3.lead-magnet"], t:"Lead magnet", d:"Something useful given away to make hand-raising easy.", s:"a free useful thing that starts the conversation"},
    {id:"f.m3.organic.a", c:["c.m3.organic"], t:"Organic", d:"Unpaid reach: content, SEO, reviews, word of mouth. Compounds.", s:"the garden: slow, then it works while you sleep"},
    {id:"f.m3.paid.a", c:["c.m3.paid"], t:"Paid / ads", d:"Bought reach. Instant, adjustable, stops when you stop.", s:"the faucet: on when you pay, off when you stop"},
    {id:"f.m3.targeting.a", c:["c.m3.targeting"], t:"Targeting", d:"Choosing who sees an ad: place, age, interests, behavior.", s:"showing it only to the right people"},
    {id:"f.m3.creative.a", c:["c.m3.creative"], t:"Creative", d:"The ad itself: image or video plus words.", s:"the ad people actually see"},
    {id:"f.m3.remarketing.a", c:["c.m3.remarketing"], t:"Remarketing", d:"Ads shown only to previous visitors. Cheap and effective.", s:"the ads that follow you, working for you"},
    {id:"f.m3.conversion-rate.a", c:["c.m3.conversion-rate"], t:"Conversion rate", d:"The percentage that takes the step: visitors who book, leads who buy.", s:"how many lookers become bookers"},
    {id:"f.m3.reach.a", c:["c.m3.reach"], t:"Reach / impressions", d:"How many people saw it, and how many times in total.", s:"how many eyeballs"},
    {id:"f.m3.engagement.a", c:["c.m3.engagement"], t:"Engagement", d:"Interactions: likes, comments, shares, saves. Applause, not income.", s:"applause, which is nice, but applause"},
    {id:"f.m3.algorithm.a", c:["c.m3.algorithm"], t:"Algorithm", d:"The platform's sorting system deciding who sees what.", s:"the platform deciding who sees you"},
    {id:"f.m3.crm.a", c:["c.m3.crm"], t:"CRM", d:"The system holding every customer, lead and conversation.", s:"the memory of your business"},
    {id:"f.m3.acquisition.a", c:["c.m3.acquisition"], t:"Acquisition", d:"Everything spent gaining one new customer.", s:"what a new customer costs you"},
    {id:"f.m3.retention.a", c:["c.m3.retention"], t:"Retention", d:"Keeping and reselling to existing customers.", s:"keeping the ones you already won"}
  ],
  quiz: [
    {id:"q.m3.funnel.a", c:["c.m3.funnel"], q:"You're training a new hire on the pipeline: strangers, visitors, leads, then finally...", a:["Customers","Subscribers","Followers","Reviewers"], why:"Every tool you buy closes one specific gap between two of those stations, ideally ending with customers who return and bring friends."},
    {id:"q.m3.funnel.b", c:["c.m3.funnel"], q:"A boutique gets steady website visitors from Instagram, but almost nobody buys. What does she actually need first?", a:["Fix the leak on the site","Spend more on ads to compensate","A flashier logo up top","One more social platform to try"], why:"Ads amplify whatever exists on the other end, leak included. Patch the hole before pouring in more water."},
    {id:"q.m3.garden-faucet.a", c:["c.m3.garden-faucet","c.m3.organic","c.m3.paid"], q:"A friend asks you to explain organic versus paid marketing using one simple picture. You say...", a:["The garden and the faucet","The hammer and the nail","The boat and the anchor","The compass and the river map"], why:"Paid is the faucet: instant, and it stops the second you stop paying. Organic is the garden: slow, but it keeps growing on its own."},
    {id:"q.m3.lead.a", c:["c.m3.lead"], q:"Ten thousand people follow your page. Forty people DMed you their number this month. Which number actually runs your business?", a:["The forty: you can reach them","The ten thousand: reach wins","Both count exactly the same","Neither, only paying customers count"], why:"A lead is a raised hand with a way to reach them. You cannot personally message ten thousand strangers."},
    {id:"q.m3.lead-magnet.a", c:["c.m3.lead-magnet"], q:"A rental shop offers a free five minute site check in exchange for one DM. A skeptical friend asks if that's just clickbait. What's the honest test?", a:["Worth something either way","Just needs to collect an email","Tease enough to make them curious","Cost the business nothing at all"], why:"Generosity is the marketing. If it wouldn't be useful on its own, it is not a real lead magnet, it is bait."},
    {id:"q.m3.algorithm.a", c:["c.m3.algorithm","c.m3.crm"], q:"A friend brags about her ten thousand followers. You ask what happens if Instagram vanished tomorrow. She goes quiet. What's the honest lesson?", a:["Followers are rented, a list is owned","Followers matter more than any list","Instagram would never actually vanish","Follower count is the only real metric"], why:"The algorithm decides who sees a follower. Nobody decides who's on your own list but you."},
    {id:"q.m3.paid.a", c:["c.m3.paid"], q:"A client tried Facebook ads for exactly one week, spent 50 euros, got nothing, and swears ads don't work. What actually happened?", a:["The ads never got time to learn","Facebook ads never work for small shops","The platform quietly kept the budget","She used the wrong kind of card"], why:"Ads need learning time, and they amplify whatever page they land on, including broken ones."},
    {id:"q.m3.crm.a", c:["c.m3.crm"], q:"You look for your business's list of past customers to send a quick thank you message. There isn't one. What's actually missing?", a:["A CRM: the business's memory","A CMS to edit the site","A bigger marketing budget","A dedicated social media manager"], why:"A CRM holds every customer and conversation in one place, so remembering someone isn't one person's job to forget."},
    {id:"q.m3.retention.a", c:["c.m3.retention"], q:"A gym signs up forty new members every January and quietly loses half of last year's by March. What's the actual pattern here?", a:["A forgetting-customers problem","Simply not enough new members joining","A pricing problem that needs fixing","A staffing problem during busy season"], why:"Most businesses aren't short on new customers. They're short on remembering and keeping the ones they already won."},
    {id:"q.m3.targeting.a", c:["c.m3.targeting"], use:"mastery", q:"A windsurf school runs one ad shown to literally everyone in the whole country, tourists and landlocked office workers alike. What's the costly mistake?", a:["Bad targeting, wrong people","The creative isn't exciting enough","Not enough money behind the ad","The wrong social platform entirely"], why:"Targeting means the ad only shows to people who could plausibly say yes. Reach everyone and you mostly pay to be ignored."}
  ],
  translate: [
    {id:"t.m3.funnel.a", c:["c.m3.funnel"], setup:"Explain the funnel without saying 'funnel'.", a:["A bucket with a hole, carried tap to garden. Patch the hole, don't add more water.","We analyze your full-funnel conversion metrics.","It is the customer journey from awareness to purchase."], why:"The leaking bucket makes 'find the leak first' unforgettable."},
    {id:"t.m3.garden-faucet.a", c:["c.m3.garden-faucet","c.m3.organic","c.m3.paid"], setup:"Explain ads versus content to a skeptical restaurant owner.", a:["A guy shouting on the corner stops when you stop paying him. Content is your reputation, always on.","Paid media delivers immediate reach while organic builds compounding equity.","We recommend a 70/30 paid-organic split."], why:"The shouting guy and the reputation need no marketing degree, and the skeptic keeps his guard down."},
    {id:"t.m3.remarketing.a", c:["c.m3.remarketing"], use:"mastery", setup:"Explain remarketing to someone who finds those ads creepy.", a:["Someone eyes a shirt and leaves. Remarketing taps the shoulder later, only for people who already looked.","Retargeting pixels track user sessions for behavioral advertising.","It is cookie-based audience segmentation."], why:"The tap on the shoulder turns creepy into considerate, and pixels-and-cookies turns considerate back into creepy."}
  ],
  diagnose: [
    {id:"d.m3.engagement.a", c:["c.m3.engagement","c.m3.funnel"], say:"'I post every day and get nothing from it.'", a:["Applause content, or a leak somewhere","Just not using enough hashtags lately","The algorithm has it out for you today"], why:"Content works when it teaches something useful and ends with one small step, and someone answers fast when a hand goes up."},
    {id:"d.m3.retention.a", c:["c.m3.retention"], use:"mastery", say:"'We are packed in season and dead the rest of the year.'", a:["Retention: never captured before","More ads during the dead months","A cheaper menu for the off season"], why:"The gold is already in the house: the people who loved it and were never asked for a way to reach them."},
    {id:"d.m3.lead.a", c:["c.m3.lead"], say:"'Leads message us and then go quiet.'", a:["Follow-up: too slow, no system","The website loads too slowly","The logo does not inspire trust"], why:"The lead who messaged Tuesday and heard back Friday bought elsewhere Wednesday."},
    {id:"d.m3.conversion-rate.a", c:["c.m3.conversion-rate"], use:"mastery", say:"'We got twice as many visitors this month after boosting posts, but bookings barely moved.'", a:["Conversion: not converting visitors","Just needs an even bigger ad budget","The boosted posts reached the wrong app"], why:"More traffic without a better conversion rate just means more people leaving unconvinced, faster."}
  ]
},
{
  id: "m4", num: "M4", title: "AI & Education", icon: "🤖",
  read: "modules/academy-module-4.html",
  cards: [
    {id:"f.m4.ai.a", c:["c.m4.ai"], t:"AI", d:"Software handling judgment-flavored tasks: reading, writing, sorting, deciding.", s:"software that can read and write, not just follow rules"},
    {id:"f.m4.llm.a", c:["c.m4.llm"], t:"LLM / model", d:"The engine: software trained on huge amounts of text to continue any text sensibly.", s:"the engine that has read almost everything"},
    {id:"f.m4.llm.b", c:["c.m4.llm"], t:"ChatGPT / Claude / Gemini", d:"Brands of models from different companies. Same kind of machine.", s:"brands, like car brands, the setup matters more"},
    {id:"f.m4.prompt.a", c:["c.m4.prompt"], t:"Prompt", d:"The instruction given to the AI. Quality in, quality out.", s:"the briefing you give it"},
    {id:"f.m4.context.a", c:["c.m4.context"], t:"Context", d:"What the model can see right now: the conversation and whatever you fed it.", s:"its short-term memory"},
    {id:"f.m4.hallucination.a", c:["c.m4.hallucination"], t:"Hallucination", d:"Confident false statements, produced because plausible is not true.", s:"nonsense, said with confidence"},
    {id:"f.m4.chatbot.a", c:["c.m4.chatbot"], t:"Chatbot", d:"Chat-window AI that answers questions and does nothing else.", s:"a receptionist that can only talk"},
    {id:"f.m4.assistants.a", c:["c.m4.assistants"], t:"Assistant", d:"AI that performs tasks on request, one at a time.", s:"does the task when you ask"},
    {id:"f.m4.agent.a", c:["c.m4.agent"], t:"Agent", d:"AI that takes steps and uses tools toward a goal, then presents the result.", s:"it does the legwork and brings you the result"},
    {id:"f.m4.ai-workflow.a", c:["c.m4.ai-workflow"], t:"AI workflow", d:"A fixed chain where AI handles some steps and rules handle the rest.", s:"an assembly line with AI at some stations"},
    {id:"f.m4.human-loop.a", c:["c.m4.human-loop"], t:"Human in the loop", d:"Design where a person approves before anything goes out. The pro standard.", s:"the machine prepares, you keep the yes"},
    {id:"f.m4.grounding.a", c:["c.m4.grounding"], t:"Grounding", d:"Connecting AI to the business's real data so answers come from facts.", s:"giving it your real prices and rules to quote from"},
    {id:"f.m4.training.a", c:["c.m4.training"], t:"Training", d:"How a model learned: patterns from massive text, fixed at build time.", s:"what it learned in school, before it met you"}
  ],
  quiz: [
    {id:"q.m4.fast-junior.a", c:["c.m4.fast-junior"], q:"Your new AI drafts ten quotes before your coffee's even done. What's the catch?", a:["It's fast, but check its work","It thinks the way a person does","It's really just a search engine","It only works for big companies"], why:"Think of it as a very fast junior with no judgment of its own. You don't marvel at it, you manage it."},
    {id:"q.m4.fast-junior.b", c:["c.m4.fast-junior"], q:"A rep worries out loud that AI will replace him at his job. What's the honest reply?", a:["You stop paying seniors for junior work","It slowly replaces your whole role over time","No, AI genuinely cannot do real work","Only inside big head offices, not here"], why:"You don't fire your team because a junior joined. You stop paying someone senior to do junior-level tasks."},
    {id:"q.m4.grounding.a", c:["c.m4.grounding","c.m4.context"], q:"A shop owner tries ChatGPT and calls the replies generic and useless. What actually happened?", a:["Nobody fed it the real prices and rules","The AI model itself is simply broken today","ChatGPT only understands English properly","She needs to pay for the paid plan"], why:"It knows the whole internet, not her shop. Feed it the real prices and rules and the answers stop being generic."},
    {id:"q.m4.prompt.a", c:["c.m4.prompt"], q:"Two reps ask the same AI for a quote email. One gets junk, one gets something usable. What's different?", a:["One gave it two real examples first","One used more exclamation marks","One typed the request in all caps","One kept the request under ten words"], why:"Show, don't describe. Two real examples of how you write beat any adjective about tone."},
    {id:"q.m4.agent.a", c:["c.m4.agent","c.m4.chatbot","c.m4.assistants"], q:"You're training a new hire on the AI ladder: talks only, does one task on request, then finally...", a:["Takes several steps and brings you the result","Sorts and replies to every email in the inbox on its own","Only ever works during business hours","Always writes in perfect grammar"], why:"Chatbot only talks. Assistant does one task when asked. Agent takes the steps itself and brings you the result to sign off on."},
    {id:"q.m4.hallucination.a", c:["c.m4.hallucination"], q:"The AI states your shop's return policy with total confidence. It's wrong. Why does this happen?", a:["It continues text that sounds right, not true","It's having an unusually slow, glitchy day","It quietly ran out of real memory partway through and guessed","It's testing you on purpose, oddly"], why:"Plausible is not the same as true. It doesn't know it's wrong, which is exactly why a person checks before it reaches a customer."},
    {id:"q.m4.hallucination.b", c:["c.m4.hallucination","c.m4.human-loop"], q:"A rep tells a wary client upfront that the AI sometimes gets things wrong. Why is that smart?", a:["Naming the limits earns more trust","It lowers expectations so you can underdeliver","Clients secretly enjoy pessimism","Some law requires that disclosure"], why:"The hype sellers hide the fine print. Naming a real limit on camera is what makes you the one they trust."},
    {id:"q.m4.context.a", c:["c.m4.context","c.m4.training"], q:"An owner asks if it's safe to paste customer names into a free AI tool online. What's the honest answer?", a:["Check the tool's terms, that's the real risk","Nothing about AI is ever safe, period","AI companies genuinely cannot see any data at all","Only paper records stay truly safe"], why:"Real business terms exist where your data isn't used for training. The actual risk is staff pasting client details into random free tools."},
    {id:"q.m4.assistants.a", c:["c.m4.assistants","c.m4.ai"], q:"A rep is pitching an AI tool and keeps saying 'artificial intelligence' over and over. What should she be selling instead?", a:["The Tuesday afternoon it gives her back","The impressive, cutting edge new technology itself","A cheaper monthly subscription plan","The future of her whole industry"], why:"Nobody wants an AI implementation. They want the quote written in four minutes and an evening back."},
    {id:"q.m4.llm.a", c:["c.m4.llm"], use:"mastery", q:"A friend says ChatGPT, Claude and Gemini are basically different species of software. What's the honest correction?", a:["Different brands, same kind of engine underneath","Actually yes, completely different technology","Only ChatGPT is truly a real AI, the rest are just copies","They're identical in every possible way"], why:"Think car brands, not different species. The setup around any of them matters more than which badge is on it."}
  ],
  translate: [
    {id:"t.m4.llm.a", c:["c.m4.llm"], setup:"Explain what an LLM is at a kitchen table.", a:["A brilliant new hire who's read every book, but started this morning","A large language model, formally trained on truly internet-scale text corpora","A neural network that predicts the next token."], why:"The new-this-morning hire captures both the brilliance and the blind spots in one line."},
    {id:"t.m4.agent.a", c:["c.m4.agent","c.m4.chatbot"], setup:"Explain an agent versus a chatbot, plainly.", a:["A chatbot only talks. An agent runs the errand for you","An agent has tool-use capabilities and multi-step reasoning.","Agents are autonomous, chatbots are reactive."], why:"The runner who brings you the paper to sign keeps the whole idea in one picture, including who stays in charge."},
    {id:"t.m4.hallucination.a", c:["c.m4.hallucination"], setup:"Explain hallucination to a nervous client.", a:["That friend who never says 'I don't know', and answers anyway","Models exhibit measurable confabulation under real distributional shift.","Hallucination rates are below 5% on benchmarks."], why:"Everyone has that friend. Nobody has a distributional shift, and that's exactly the point."},
    {id:"t.m4.context.a", c:["c.m4.context"], use:"mastery", setup:"Explain 'context' to a client who just says the AI 'doesn't know anything.'", a:["It only knows what you've actually told it, so far","Context refers to the token window available to the model.","It requires a larger context length parameter."], why:"Its short-term memory is the whole conversation. Feed it real numbers, and it stops sounding clueless."}
  ],
  diagnose: [
    {id:"d.m4.grounding.a", c:["c.m4.grounding","c.m4.context","c.m4.fast-junior"], say:"'We tried ChatGPT and the answers were too generic.'", a:["No onboarding: it never learned their prices or rules","The model is simply too small, so buy a much bigger one","AI simply doesn't fit their industry"], why:"Generic in, generic out. Their failed experiment is your setup pitch, without criticizing anything they tried."},
    {id:"d.m4.human-loop.a", c:["c.m4.human-loop","c.m4.chatbot"], say:"'My customers will hate talking to a robot.'", a:["They hate bad ones. Let it answer fast, hand off honestly","They're completely right, never use AI with customers at all","Customers can't actually tell the difference"], why:"Fast and correct is what customers actually want. A well designed setup delivers more of both, honestly."},
    {id:"d.m4.context.a", c:["c.m4.context","c.m4.training"], say:"'Someone on my team is probably already pasting client details into free AI tools.'", a:["Shadow AI: make it official and safe","Fire the employee immediately, no questions asked","Just block the whole internet at work entirely"], why:"It's already happening, quietly, with real customer data. A policy and picked tools beats pretending it isn't."},
    {id:"d.m4.ai-workflow.b", c:["c.m4.ai-workflow","c.m4.human-loop"], use:"mastery", say:"'We want AI to handle the whole booking process end to end, no humans at all.'", a:["Some stations need rules, one needs a human yes","Sure, that's exactly what AI is built for, apparently","Impossible, AI can't touch bookings at all","Only really big companies can pull that off"], why:"Picture the assembly line: rules run some stations, AI runs others, and a person still signs off before anything reaches a customer."},
    {id:"d.m4.prompt.a", c:["c.m4.prompt"], use:"mastery", say:"'I asked it to write something for our newsletter and got total generic filler.'", a:["The instruction itself was too vague","The AI tool is simply a bad one","Newsletters just aren't AI-shaped work","She needs a more expensive AI plan"], why:"Vague brief, vague draft. A specific ask, like the topic, the tone and one example, gets a specific result back."}
  ]
},
{
  id: "m5", num: "M5", title: "Systems & Software", icon: "🗄️",
  read: "modules/academy-module-5.html",
  cards: [
    {id:"f.m5.database.a", c:["c.m5.database"], t:"Database", d:"The structured filing cabinet where all business data lives, with rules enforced.", s:"one list that is always right"},
    {id:"f.m5.backend.a", c:["c.m5.backend"], t:"Backend", d:"The rules layer: what happens when a booking, payment or date event fires.", s:"the machinery behind the screens"},
    {id:"f.m5.frontend.a", c:["c.m5.frontend"], t:"Frontend", d:"The screens: customer site and team dashboard.", s:"everything people actually see and touch"},
    {id:"f.m5.api.a", c:["c.m5.api"], t:"API", d:"The official plug a system offers so other software can talk to it.", s:"the plug that lets systems connect"},
    {id:"f.m5.webhook.a", c:["c.m5.webhook"], t:"Webhook", d:"The doorbell: a system pings yours the instant something happens.", s:"the doorbell between systems"},
    {id:"f.m5.integration.a", c:["c.m5.integration"], t:"Integration", d:"A finished bridge: two systems exchanging data with no human messenger.", s:"your tools finally talk to each other"},
    {id:"f.m5.dashboard.a", c:["c.m5.dashboard"], t:"Dashboard", d:"A glanceable screen showing the state of the business.", s:"everything on one screen"},
    {id:"f.m5.back-office.a", c:["c.m5.back-office"], t:"Back office", d:"The internal screens where the team runs the operation.", s:"the control room behind your website"},
    {id:"f.m5.internal-tool.a", c:["c.m5.internal-tool"], t:"Internal tool", d:"Software only the team sees; customers never touch it.", s:"software just for your team"},
    {id:"f.m5.booking-engine.a", c:["c.m5.booking-engine"], t:"Booking engine", d:"The availability-request-approval core of a reservation system.", s:"the part that knows what is free and takes the ask"},
    {id:"f.m5.realtime.a", c:["c.m5.realtime"], t:"Sync / real-time", d:"All screens reflecting the same data at the same moment.", s:"everyone sees the same thing, instantly"},
    {id:"f.m5.migration.a", c:["c.m5.migration"], t:"Migration", d:"Moving data from an old system to a new one without losing history.", s:"a careful move, nothing gets left behind"},
    {id:"f.m5.uptime.a", c:["c.m5.uptime"], t:"Uptime", d:"The share of time a system is running. Monitored, not hoped.", s:"how often it is simply working"},
    {id:"f.m5.backup.a", c:["c.m5.backup"], t:"Backup", d:"Automatic copies of the data, so one bad day cannot erase the memory.", s:"a spare copy of everything, made automatically"},
    {id:"f.m5.permissions.a", c:["c.m5.permissions"], t:"Access / permissions", d:"Who can log in and what each person is allowed to do.", s:"the right keys for the right people"},
    {id:"f.m5.cloud.a", c:["c.m5.cloud"], t:"The cloud", d:"Software and data running on professional servers you reach via the internet.", s:"it lives on professional computers, not under the counter"}
  ],
  quiz: [
    {id:"q.m5.three-layers.b", c:["c.m5.three-layers"], q:"A client says her business 'just feels chaotic', though nothing specific seems broken. What's the fastest systems checkup?", a:["Check which layer is missing or got doubled","Check how many browser tabs are currently open","Check exactly when the website was last completely redesigned, in full","Check if a competitor recently undercut her on price"], why:"Every system is three layers: a place data lives, rules that move it, screens people touch. When a business feels broken, one of the three is usually missing or doubled."},
    {id:"q.m5.three-layers.c", c:["c.m5.three-layers"], q:"A regular texts to ask why the scooter she was 'definitely holding' just got rented to someone else. What actually broke?", a:["Two screens both claimed the truth","She simply waited a few minutes too long","The scooter developed a mechanical fault","Staff forgot to write her name down"], why:"A double booking is never bad luck. It is two lists disagreeing about one scooter, and the fix is one list everything reads from."},
    {id:"q.m5.database.b", c:["c.m5.database"], q:"Two staff both have the booking spreadsheet open on a busy Saturday. What is the honest risk?", a:["One save can quietly overwrite the other","The file just takes longer to open when shared","Only whoever saved most recently can undo changes","The spreadsheet needs a paid subscription upgrade"], why:"A spreadsheet trusts everyone typing into it to be careful forever. A database simply refuses to let two people save over the same booking."},
    {id:"q.m5.api.b", c:["c.m5.api"], q:"A client asks if her booking tool can 'talk to' her accounting software. What are you actually checking first?", a:["Whether either tool has a plug to connect through","How much both monthly subscriptions actually cost together","Which company designed the nicer logo","How many years both tools have existed"], why:"That plug is an API. Good modern tools have one. A closed box without an API is the real warning sign, not the price."},
    {id:"q.m5.cloud.b", c:["c.m5.cloud"], q:"A guest house owner keeps all her booking data on a laptop under the counter, to avoid a monthly cloud storage fee. What's the honest risk?", a:["Theft or a crash loses everything at once","Local storage feels more private and secure","Cloud services almost always cost more overall","The laptop's fan runs a bit louder than a server"], why:"Guarded data centers and continuous backups beat a laptop that can be stolen or spilled on. The monthly fee buys real insurance, not just storage."},
    {id:"q.m5.webhook.a", c:["c.m5.webhook"], q:"A rental shop owner refuses to hand over the keys until he's sure a deposit landed. What system actually gives him that certainty?", a:["A webhook: payment tells the booking", "Checking the bank app every single hour, all day", "Trusting the customer's word on it", "Only ever accepting cash in person"], why:"A webhook rings the booking system the instant a payment lands. No more refreshing a bank app all day, hoping."},
    {id:"q.m5.permissions.a", c:["c.m5.permissions"], use:"mastery", q:"A part-time weekend hire can see this month's total revenue and last year's supplier invoices, along with today's bookings. What's actually missing?", a:["Permissions scoped to her actual job","A password reset, since logins get shared around","More training so she uses the data responsibly","Nothing, more visibility is always better"], why:"Permissions are the right keys for the right people. A weekend hire needs today's calendar, not last year's supplier invoices."}
  ],
  translate: [
    {id:"t.m5.three-layers.a", c:["c.m5.three-layers"], setup:"Explain why 'everyone needs one shared system' actually matters, at a kitchen table.", a:["Three calendars means someone misses the party. One on the fridge fixes it for good.","We centralize your fully canonical data model across every single touchpoint and device.","It is a normalized, deduplicated, single source of truth database architecture."], why:"The three calendars are every business running on three lists that quietly disagree. One shared place fixes the disagreement, not the people."},
    {id:"t.m5.integration.a", c:["c.m5.integration"], setup:"Explain what an integration actually buys a business, plainly.", a:["You stop being the messenger between your own two systems.","We implement bidirectional data synchronization via REST APIs.","Systems interoperate through webhook-driven event flows continuously."], why:"Right now the owner reads it here and types it there. An integration means the machines pass the note themselves."},
    {id:"t.m5.migration.a", c:["c.m5.migration"], setup:"A client worries switching systems means starting from zero. What's the honest answer?", a:["Nothing starts from zero. Every booking gets checked off, one by one.","Our ETL pipeline preserves full referential integrity throughout.","We execute a fully phased data migration with complete rollback capability built in."], why:"Migration is a careful move with a checklist, not a demolition. Nothing about the old bookings gets left on the curb."},
    {id:"t.m5.uptime.a", c:["c.m5.uptime"], use:"mastery", setup:"A client assumes 'reliable hosting' just means paying more money. Explain uptime honestly.", a:["We know before you do, with a fix path already ready.","We provide guaranteed SLA-backed infrastructure redundancy across every region, continuously.","Our systems leverage a multi-region failover architecture."], why:"Money buys monitoring and a fix path, not a promise nothing ever breaks. The honest pitch is speed of response."}
  ],
  diagnose: [
    {id:"d.m5.three-layers.b", c:["c.m5.three-layers"], say:"'We double-booked again last weekend.'", a:["Two lists disagreeing, not bad luck","Staff carelessness that needs more discipline","Simply too many customers wanting the same weekend"], why:"Two lists eventually always disagree. One list that everything reads from is the structural fix, not a stern talking-to."},
    {id:"d.m5.permissions.a", c:["c.m5.permissions"], say:"'Only I can see the agenda. It's on my phone.'", a:["Nobody else has the keys to look","Perfectly fine for a small operation","Just needs a newer, faster phone model"], why:"Permissions means the right people have the right keys. Right now exactly one person can even open the door."},
    {id:"d.m5.backup.a", c:["c.m5.backup"], say:"'If my laptop died tonight, honestly, everything would be gone.'", a:["No backups, the cheapest insurance missing","Time to simply buy a much sturdier and more expensive laptop","Print out every single record weekly"], why:"A backup is a spare copy made automatically. It is the cheapest insurance in the business, and it takes an afternoon."},
    {id:"d.m5.back-office.a", c:["c.m5.back-office"], use:"mastery", say:"'My team still texts each other to ask if a scooter got returned, even though we paid for a whole system.'", a:["No back office: staff never got their own screens","A discipline problem, staff should just check better","Simply needs a faster group chat app for the team"], why:"The team needs the same live data the booking system already has, just a screen built for them. That is the back office, not a second app."},
    {id:"d.m5.booking-engine.a", c:["c.m5.booking-engine"], use:"mastery", say:"'Customers can request any date on the calendar, even ones we already gave away this morning.'", a:["The engine skips the real availability check","The customers keep making an honest mistake","The calendar app genuinely needs a software update, nothing more"], why:"A booking engine's whole job is checking what's actually free before taking the request. Skip that check and the calendar becomes a suggestion, not a promise."}
  ]
},
{
  id: "m6", num: "M6", title: "The Sales Arena", icon: "🎯",
  read: "modules/academy-module-6.html",
  cards: [
    {id:"f.m6.spine.a", c:["c.m6.spine"], t:"The conversation spine", d:"Listen, dig, diagnose, translate, recommend, close-lite. Mostly listening.", s:"six moves, in order, mostly listening"},
    {id:"f.m6.two-thirds.a", c:["c.m6.two-thirds"], t:"The two-thirds ratio", d:"The prospect talks about two thirds of the time in good discovery.", s:"if you are explaining before asking four questions, you are pitching"},
    {id:"f.m6.insider-question.a", c:["c.m6.insider-question"], t:"Insider question", d:"A question about a moment only insiders know exists. Proof no slide can match.", s:"asking about the late return proves you have stood there"},
    {id:"f.m6.tuesday-move.a", c:["c.m6.tuesday-move"], t:"The Tuesday move", d:"When an answer is vague, ask what it looks like on a normal Tuesday.", s:"the truth lives in the boring Tuesday"},
    {id:"f.m6.normalization.a", c:["c.m6.normalization"], t:"Honest normalization", d:"'You are not the exception, we see this in almost every business.' Only when true.", s:"shame closes people, normalcy opens them"},
    {id:"f.m6.reflect-first.a", c:["c.m6.reflect-first"], t:"Reflect before recommend", d:"Repeat their worst moments back in their words before proposing anything.", s:"feeling understood comes before feeling helped"},
    {id:"f.m6.one-recommendation.a", c:["c.m6.one-recommendation"], t:"One recommendation", d:"Not a menu. The smallest move that fixes the biggest leak.", s:"you were hired to have an opinion"},
    {id:"f.m6.close-lite.a", c:["c.m6.close-lite"], t:"Close-lite", d:"A concrete small next step with a date. Never 'think about it'.", s:"I will send the audit Thursday"},
    {id:"f.m6.story-arc.a", c:["c.m6.story-arc"], t:"Situation-turn-takeaway", d:"The 30-second story shape, always ending with a handback question.", s:"...does any of that sound like your evenings?"}
  ],
  quiz: [
    {id:"q.m6.spine.a", c:["c.m6.spine"], q:"You're on a call and catch yourself explaining pricing before asking a single question. What actually went wrong?", a:["You skipped listening and diagnosing","You're just saving everyone time","Nothing, price transparency builds trust","You should have opened with a discount"], why:"The spine runs listen, dig, diagnose, translate, recommend, close-lite, in that order. Skip to price and you're pitching, not diagnosing."},
    {id:"q.m6.two-thirds.a", c:["c.m6.two-thirds"], q:"The prospect is halfway through describing her booking chaos. You already know the fix. You...", a:["Keep asking, let her finish","Jump in with the fix to save her time","Summarize what you've heard so far","Ask if she wants to see pricing now"], why:"Two thirds theirs, one third yours. Cutting in early trades a real diagnosis for a guess."},
    {id:"q.m6.one-recommendation.a", c:["c.m6.one-recommendation"], q:"The prospect asks you to email over three different package options so she can compare them.", a:["Send one recommendation, not three","Send all three, let her pick freely","Send four options for a fuller picture","Ask her to name a budget first"], why:"A menu makes her the expert, and she's not, so she stalls. You were hired to have an opinion."},
    {id:"q.m6.story-arc.a", c:["c.m6.story-arc"], q:"You just finished your thirty second story about the scooter rental owner. What's the last thing you say?", a:["'Sound like your evenings at all?'","'And that's why we're the best around'","Nothing, just let the silence sit there","'Anyway, back to your situation'"], why:"Situation, turn, takeaway, then hand it back. The question keeps the story hers, not yours."},
    {id:"q.m6.normalization.a", c:["c.m6.normalization"], q:"The prospect admits, almost apologizing, that she still tracks bookings on paper.", a:["'You are not the exception here.'","'Wow, that's pretty behind the times.'","'Don't worry, we'll fix that embarrassment fast.'","Nothing, just move to the next question"], why:"Only say it when it's true. Shame closes people, normalcy opens them, and the confession gets safer."},
    {id:"q.m6.close-lite.a", c:["c.m6.close-lite"], q:"You wrap up a great meeting. The prospect says 'let me think it over and get back to you.'", a:["'Fair enough. Thursday, either way.'","'Sure, take your time, no rush at all.'","'Okay! Talk soon.'","'Would a discount help you decide faster?'"], why:"Fog is where great conversations go to die. Anchor a concrete next step even when they stall."},
    {id:"q.m6.two-thirds.b", c:["c.m6.two-thirds"], use:"mastery", q:"A rep brags that she 'let the prospect talk the whole time' and got zero questions in. Good discovery?", a:["No, two thirds isn't zero, ask something","Yes, silence is always the strategy","No, you should be doing most of the talking","Yes, rambling beats structured questions"], why:"Two thirds theirs, one third yours. All ears with no diagnostic questions isn't real discovery either."}
  ],
  translate: [
    {id:"t.m6.insider-question.a", c:["c.m6.insider-question"], setup:"You're opening discovery with a rental shop owner. Which question actually gets her talking?", a:["The late return, next renter waiting, what happens?","Do you have any challenges with your booking process?","Would you say operational efficiency is a priority this quarter?"], why:"The first names a moment only operators know. The others are generic discovery that caps trust and Arena scores alike."},
    {id:"t.m6.tuesday-move.a", c:["c.m6.tuesday-move"], setup:"The prospect gave a vague answer: 'oh, bookings mostly go fine.' Your move?", a:["What does 'mostly' look like on a normal Tuesday?","Great, then let us talk about your website.","Statistics show 40% of rentals lose bookings to slow replies."], why:"Send vague answers to Tuesday. Owners describe ideals and exceptions; the truth lives in the boring Tuesday."},
    {id:"t.m6.reflect-first.a", c:["c.m6.reflect-first"], setup:"You just heard their chaos story. Before recommending, you...", a:["Reflect their situation back, in their words.","Present your three-tier pricing.","Tell them about another client with worse problems."], why:"Feeling understood comes before feeling helped, always, and cannot be skipped."},
    {id:"t.m6.translation-rule.a", c:["c.m6.translation-rule"], setup:"The prospect asks what 'we're setting up an API integration' actually gets her.", a:["Your booking and invoice finally agree with each other","A RESTful connection between your two platforms","Bidirectional data synchronization between systems"], why:"Translate any fix into more customers, looking professional, or less hassle. Nobody hires you for the API."},
    {id:"t.m6.one-recommendation.a", c:["c.m6.one-recommendation"], use:"mastery", setup:"A new hire asks why you never send three pricing options in one email.", a:["A menu makes them the expert, not you.","Because more options means more admin for us","Because clients get confused by numbers"], why:"One recommendation isn't a shortcut, it's confidence. A menu outsources the decision to someone who isn't equipped to make it."}
  ],
  diagnose: [
    {id:"d.m6.spine.a", c:["c.m6.spine"], say:"'Nobody can find us online.'", a:["Findability: Module 1 territory","Conversion: Pack 01 territory","Follow-up speed: Module 3 territory"], why:"SEO, the Google profile, or simply no presence. Check the map box first for a local business."},
    {id:"d.m6.spine.b", c:["c.m6.spine"], say:"'We get visitors but no bookings.'", a:["Conversion: Pack 01 territory","Findability: Module 1 territory","AI: Module 4 territory"], why:"Speed, clarity or proof is failing. Run the five second test together."},
    {id:"d.m6.spine.c", c:["c.m6.spine"], say:"'Customers always haggle on price.'", a:["Positioning: Module 2 territory","Systems: Module 5 territory","Ads: Module 3 territory"], why:"They look interchangeable. Nobody haggles with the specialist."},
    {id:"d.m6.spine.d", c:["c.m6.spine"], say:"'I post constantly and nothing happens.'", a:["Pipeline: Module 3 territory","Branding: Module 2 territory","Bottleneck: Pack 02 territory"], why:"Applause content, or a leak further down. Follow the pipeline."},
    {id:"d.m6.spine.e", c:["c.m6.spine"], say:"'I am drowning in admin.'", a:["Bottleneck: Pack 02 territory","Messaging: Module 2 territory","SEO: Module 1 territory"], why:"Manual work a system should do. Walk the bottleneck bill with her own numbers."},
    {id:"d.m6.spine.f", c:["c.m6.spine"], say:"'We should do something with AI.'", a:["Automation first: Pack 02 territory","An AI agent, built immediately","Just needs a website redesign"], why:"Find the repeated task first. Half of what owners call AI is plain automation."},
    {id:"d.m6.spine.g", c:["c.m6.spine"], say:"'We double-booked again last weekend.'", a:["Systems: Module 5 territory","Staff discipline problem","Marketing success, actually"], why:"Two lists disagreeing about one scooter. One list, everything reads from it."},
    {id:"d.m6.spine.h", c:["c.m6.spine"], say:"'People pick the big agency down the street.'", a:["Positioning: Module 2 territory","Undercut the agency on price","Just bad luck, keep trying"], why:"The big agency wins on familiar, not on better. Positioning and proof close that gap."},
    {id:"d.m6.normalization.a", c:["c.m6.normalization"], use:"mastery", say:"'Honestly, we're the only ones still doing this all by hand, aren't we?'", a:["Skip it if untrue, say so honestly","Say it anyway, it always helps close","Ignore it, move straight to pricing"], why:"Honest normalization only works when it's true. False comfort gets caught, and trust doesn't come back."},
    {id:"d.m6.close-lite.a", c:["c.m6.close-lite"], use:"mastery", say:"'Great meeting! Let's touch base again sometime next month.'", a:["Trade it for a real date: 'Thursday?'","Say 'sounds good' and end the call there","Offer a discount to speed the decision"], why:"'Sometime next month' is fog with a calendar attached. Trade it for one real date before you hang up."}
  ]
}
];
