/* Salty Academy data · open-answer and matching items. Task 13 fills in the rest. */
window.ACADEMY_OPEN = {
  p1: [
    { id:"o.p1.speed.a", c:["c.p1.speed"], use:"module",
      ask:"A cafe owner says her site is fine, it just takes a few seconds. What do you tell her?",
      rubric:{ must:[["slow","seconds","speed","load"],["leave","lose","gone","bounce","back"]],
               nice:[["never","silent","complain","tell you"]],
               miss:[{ match:["google","ranking","seo"],
                       say:"Speed does affect ranking, but the money problem is the visitor who left before the page appeared." }],
               minMust:1 },
      model:"Three seconds of blank screen feels the same as a broken site. Most phone visitors leave, and none of them complain, so she never hears about it.",
      why:"The point is the silence: she cannot see the customers she lost." },
    { id:"o.p1.value-prop.a", c:["c.p1.value-prop"], use:"module",
      ask:"A client's homepage says 'We are passionate about quality and service.' What do you actually tell her?",
      rubric:{ must:[["generic","vague","meaningless","interchangeable","competitor","anybody"],
                      ["specific","concrete","unique","specialize","different","details"]],
               nice:[["rival","competitor","truthfully","identical"]],
               miss:[{ match:["stronger","better","impressive","exciting"],
                       say:"Adding stronger adjectives does not fix it. It still needs to say something no competitor could truthfully claim." }] },
      model:"That line could sit on any competitor's homepage and nobody would notice, so it isn't actually selling anything. Replace it with the one specific thing only this business can truthfully say, like exactly how fast a booking gets confirmed.",
      why:"The copy-paste test: if a rival could paste it onto their own site, it proves nothing." },
    { id:"o.p1.friction.a", c:["c.p1.friction"], use:"mastery",
      ask:"A rental booking form asks for a company name, a job title and a referral source before the date. What's actually happening here?",
      rubric:{ must:[["unnecessary","irrelevant","pointless","overkill","excessive"],
                      ["abandon","hesitate","frustrated","reconsider","disappear"]],
               nice:[["strip","simplify","remove","shorten"]],
               miss:[{ match:["information","details","understand","useful"],
                       say:"More fields do not mean better leads. They mean fewer people finish the form at all." }] },
      model:"Every extra field the visitor doesn't need is a reason to stop and think, and thinking is exactly what a rushed visitor won't do. Strip the form down to the date and a way to reach them, and more people will actually finish booking.",
      why:"Every extra tap costs you a slice of the people who were already ready to book." },
    { id:"x.p1.value-prop.a", c:["c.p1.value-prop","c.p1.speed","c.p1.choice-overload","c.p1.proof"], use:"module",
      ask:"Match each complaint to the real problem behind it.",
      pairs:[ {l:"'I can't tell what she actually sells'", r:"A weak value proposition"},
              {l:"'The page took forever, I gave up'", r:"A slow load time"},
              {l:"'There were three buttons, I picked none'", r:"Choice overload"},
              {l:"'It looked fine but had no reviews anywhere'", r:"Missing social proof"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." }
  ],
  p2: [
    { id:"x.p2.bottleneck.a", c:["c.p2.bottleneck","c.p2.workflow"], use:"module",
      ask:"Match each complaint to what is actually broken.",
      pairs:[ {l:"'I retype every booking into the calendar'", r:"Manual entry"},
              {l:"'Nobody knows which list is current'", r:"No single source of truth"},
              {l:"'It only jams on Saturdays'", r:"A bottleneck"} ],
      why:"Each complaint names a symptom, and the match is the real fault behind it." }
  ]
};
