/* Salty Academy data · open-answer and matching items. Task 13 fills in the rest. */
window.ACADEMY_OPEN = {
  p1: [
    { id:"o.p1.speed.a", c:["c.p1.speed"], use:"module",
      ask:"A cafe owner says her site is fine, it just takes a few seconds. What do you tell her?",
      rubric:{ must:[["slow","seconds","speed","load"],["leave","lose","gone","bounce","back"]],
               nice:[["never","silent","complain","tell you"]],
               miss:[{ match:["google","ranking","seo"],
                       say:"Speed does affect ranking, but the money problem is the visitor who left before the page appeared." }],
               minMust:1 },
      model:"Three seconds of blank screen feels the same as a broken site. Most phone visitors leave, and none of them complain, so she never hears about it.",
      why:"The point is the silence: she cannot see the customers she lost." },
    { id:"o.p1.value-prop.a", c:["c.p1.value-prop"], use:"module",
      ask:"A client's homepage says 'We are passionate about quality and service.' What do you actually tell her?",
      rubric:{ must:[["generic","vague","meaningless","interchangeable","competitor","anybody"],
                      ["specific","concrete","unique","specialize","different","details"]],
               nice:[["rival","competitor","truthfully","identical"]],
               miss:[{ match:["stronger","better","impressive","exciting"],
                       say:"Adding stronger adjectives does not fix it. It still needs to say something no competitor could truthfully claim." }] },
      model:"That line could sit on any competitor's homepage and nobody would notice, so it isn't actually selling anything. Replace it with the one specific thing only this business can truthfully say, like exactly how fast a booking gets confirmed.",
      why:"The copy-paste test: if a rival could paste it onto their own site, it proves nothing." },
    { id:"o.p1.friction.a", c:["c.p1.friction"], use:"mastery",
      ask:"A rental booking form asks for a company name, a job title and a referral source before the date. What's actually happening here?",
      rubric:{ must:[["unnecessary","irrelevant","pointless","overkill","excessive"],
                      ["abandon","hesitate","frustrated","reconsider","disappear"]],
               nice:[["strip","simplify","remove","shorten"]],
               miss:[{ match:["information","details","understand","useful"],
                       say:"More fields do not mean better leads. They mean fewer people finish the form at all." }] },
      model:"Every extra field the visitor doesn't need is a reason to stop and think, and thinking is exactly what a rushed visitor won't do. Strip the form down to the date and a way to reach them, and more people will actually finish booking.",
      why:"Every extra tap costs you a slice of the people who were already ready to book." },
    { id:"x.p1.value-prop.a", c:["c.p1.value-prop","c.p1.speed","c.p1.choice-overload","c.p1.proof"], use:"module",
      ask:"Match each complaint to the real problem behind it.",
      pairs:[ {l:"'I can't tell what she actually sells'", r:"A weak value proposition"},
              {l:"'The page took forever, I gave up'", r:"A slow load time"},
              {l:"'There were three buttons, I picked none'", r:"Choice overload"},
              {l:"'It looked fine but had no reviews anywhere'", r:"Missing social proof"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." }
  ],
  p2: [
    { id:"o.p2.bottleneck-bill.a", c:["c.p2.bottleneck-bill"], use:"module",
      ask:"A client says her admin doesn't really cost her anything, she does it herself for free. How do you show her what it actually costs?",
      rubric:{ must:[["hours","multiply","calculate","fifty-two","do the math"],
                      ["yearly","forever","ongoing","recurring","adds up"]],
               nice:[["real number","concrete","specific","her own numbers"]],
               miss:[{ match:["expensive","costly","pricey"],
                       say:"Saying it's expensive isn't the same as running the actual numbers. The formula, not the adjective, is what convinces her." }] },
      model:"You do the math with her own numbers: hours spent each week times what her hour is worth times fifty two weeks, which turns ten hours into a real yearly figure like twenty six thousand euros. That number keeps repeating every year until the bottleneck is fixed, and nobody argues with their own numbers.",
      why:"The bottleneck bill turns a vague feeling of busyness into a number a client can't unsee." },
    { id:"o.p2.phone-test.a", c:["c.p2.phone-test"], use:"module",
      ask:"An owner insists everything runs fine because he personally handles it all. What question actually gets him to feel the problem?",
      rubric:{ must:[["unreachable","disconnect","offline","switch off","two weeks"],
                      ["bottleneck","dependent","reliant","without him","stuck point"]],
               nice:[["watch his face","pause","honest answer"]],
               miss:[{ match:["hire","staff","employee","assistant"],
                       say:"Hiring might eventually help, but the question is about proving he's the single point everything squeezes through, not about staffing yet." }] },
      model:"You ask if he could switch his phone off for two weeks and come back to a business that ran completely normally. Watch his face when he answers: if every booking and question squeezes through him, that isn't dedication, it's a queue with a yearly bill attached.",
      why:"The phone test turns an abstract idea into a question the owner has to answer about his own life." },
    { id:"x.p2.bottleneck.a", c:["c.p2.bottleneck","c.p2.workflow"], use:"module",
      ask:"Match each complaint to what is actually broken.",
      pairs:[ {l:"'I retype every booking into the calendar'", r:"Manual entry"},
              {l:"'Nobody knows which list is current'", r:"No single source of truth"},
              {l:"'It only jams on Saturdays'", r:"A bottleneck"} ],
      why:"Each complaint names a symptom, and the match is the real fault behind it." },
    { id:"o.p2.process-map.a", c:["c.p2.process-map"], use:"mastery",
      ask:"Before you write a single line of code for a new client, what's the actual first deliverable, and why does handing it over first matter?",
      rubric:{ must:[["write down","list","document","mapping","step by step"],
                      ["no cost","before building anything","earns trust","first time anyone"]],
               miss:[{ match:["price","quote","proposal","cost estimate"],
                       say:"A price isn't the first deliverable. The first thing is writing down how the business actually works today, before any number is discussed." }] },
      model:"Before building anything we sit down and write out exactly what the business repeats every day, step by step, including the WhatsApp back and forth. Handing that list over first costs nothing, and it's often the first time anyone has ever seen their own workflow on paper, which is what earns the trust to build the bigger thing.",
      why:"Process mapping is free, and it's usually the first time an owner has ever seen their own business written down." }
  ],
  m1: [
    { id:"o.m1.cms.a", c:["c.m1.cms"], use:"module",
      ask:"A client asks why she should care about having a CMS. What do you tell her?",
      rubric:{ must:[["herself","yourself","independently","directly","alone"],
                      ["developer","waiting","depend","stuck","someone"]],
               nice:[["minutes","password","login"]],
               miss:[{ match:["design","template","pretty","looks"],
                       say:"A CMS isn't about how the site looks, it's about who can change it and how fast." }] },
      model:"A CMS means she can log in and change a price or swap a photo herself, in minutes, instead of emailing a developer and waiting days. It's her own key to her own site, so day to day changes stop depending on someone else.",
      why:"The whole point of a CMS is independence: she stops needing to go through someone else for small changes." },
    { id:"o.m1.seo.a", c:["c.m1.seo"], use:"module",
      ask:"A client asks what SEO actually is, in plain words. What do you say?",
      rubric:{ must:[["ranking","showing","search","google","found"],
                      ["months","gradual","patience","ongoing","compounds"]],
               nice:[["clear","trust","fast"]],
               miss:[{ match:["trick","switch","guarantee","instant","overnight"],
                       say:"SEO isn't a trick you flip on. It's making the site genuinely clear and fast, and letting that compound over months." }] },
      model:"SEO is making sure Google understands what you sell and shows you to the people already searching for it. It isn't instant, and nobody can honestly guarantee a ranking, it takes months and keeps compounding the longer you stick with it.",
      why:"The point is killing two myths at once: SEO is not a trick, and it is not fast." },
    { id:"x.m1.cms.a", c:["c.m1.cms","c.m1.domain","c.m1.https","c.m1.responsive"], use:"module",
      ask:"Match each client complaint to the real problem behind it.",
      pairs:[ {l:"'I have to email someone to fix a typo'", r:"No CMS"},
              {l:"'A builder we can't reach still owns our address'", r:"No domain ownership"},
              {l:"'The browser says Not secure'", r:"Missing HTTPS"},
              {l:"'It looks perfect, except on a phone'", r:"Not responsive"} ],
      why:"Each complaint names a symptom. The match is the real fault sitting underneath it." },
    { id:"o.m1.analytics.a", c:["c.m1.analytics"], use:"mastery",
      ask:"An owner says her gut tells her most visitors come from Instagram, not Google. How do you actually find out if she's right?",
      rubric:{ must:[["analytics","numbers","tracking","measure","figures"],
                      ["sources","traffic","referral","visitors","origin"]],
               miss:[{ match:["instagram","assume","guess","probably"],
                       say:"Guessing which platform wins isn't the same as checking. Analytics shows the real traffic sources, not just the loudest one." }] },
      model:"You check her actual analytics instead of trusting a gut feeling, because it shows exactly where each visitor came from. It might confirm Instagram, or it might reveal Google was quietly doing more work the whole time.",
      why:"Analytics replaces a guess with a number. Gut feelings about traffic sources are wrong more often than owners expect." },
    { id:"o.m1.frontend.a", c:["c.m1.frontend","c.m1.backend"], use:"mastery",
      ask:"A client asks what 'frontend' and 'backend' actually mean, without any jargon. What's the plain answer?",
      rubric:{ must:[["visible","screens","buttons","customers","looks"],
                      ["hidden","machinery","behind","logic","invisible"]],
               miss:[{ match:["coding","programming","technical","complicated"],
                       say:"It's not really about how technical each part is, it's about whether a customer can see it or not." }] },
      model:"The frontend is everything a visitor actually sees and taps, the pages, the buttons, the photos. The backend is the hidden machinery behind it, the part that processes things and makes the visible part actually work, even though customers never see it directly.",
      why:"Frontend and backend split on one line: can a customer see it, or not." }
  ]
};
